/* ==========================================================================
   GENERADO por scripts/generar-meta.mjs — no editar a mano.

   Lo mínimo que hace falta para pintar la biblioteca sin descargar el texto
   de los libros: título, autor, año, las dos frases de la ficha y los minutos
   de cada capítulo, que son los que se ven parada por parada en el mapa del
   camino. El texto entero se pide aparte, al abrir un libro.

   Para regenerarlo:  npx tsx scripts/generar-meta.mjs
   ========================================================================== */

export type CapituloMeta = { titulo: string; minutos: number };

export type FichaMeta = {
  id: string;
  titulo: string;
  autor: string;
  ano: number;
  gancho: string;
  porQue: string;
  minutos: number;
  capitulos: CapituloMeta[];
};

export const META: FichaMeta[] = [
  {
    id: "sapiens",
    titulo: "Sapiens",
    autor: "Yuval Noah Harari",
    ano: 2011,
    gancho: "Nadie con antigüedad quería dar aquella asignatura de primero. Se la endosaron a un recién llegado.",
    porQue: "Cuenta la historia entera de nuestra especie en un solo hilo, y su tesis —que dominamos el planeta por creernos cosas que no existen— explica bastante más de lo que promete.",
    minutos: 25.4,
    capitulos: [
      { titulo: "Salida: la asignatura que nadie quería dar", minutos: 5.2 },
      { titulo: "Primera parada: creer en cosas que no existen", minutos: 5.1 },
      { titulo: "Segunda parada: el mayor fraude de la historia", minutos: 5 },
      { titulo: "Tercera parada: donde falla y qué no dice", minutos: 5 },
      { titulo: "Destino: la pregunta por la felicidad", minutos: 5 },
    ],
  },
  {
    id: "homo-deus",
    titulo: "Homo Deus",
    autor: "Yuval Noah Harari",
    ano: 2015,
    gancho: "Sapiens contaba de dónde venimos. Este empieza donde aquel acaba y pregunta qué haremos cuando ya no haya nada que resolver.",
    porQue: "Su primera parte es la mejor noticia que has leído nunca; la segunda es la más inquietante. Y las dos van juntas por necesidad.",
    minutos: 21.2,
    capitulos: [
      { titulo: "El hambre, la peste y la guerra", minutos: 4.6 },
      { titulo: "La muerte como problema técnico", minutos: 4.5 },
      { titulo: "El relato que nos gobierna", minutos: 4 },
      { titulo: "El algoritmo que te conoce mejor", minutos: 4.3 },
      { titulo: "Las preguntas que deja", minutos: 3.8 },
    ],
  },
  {
    id: "armas-germenes",
    titulo: "Armas, gérmenes y acero",
    autor: "Jared Diamond",
    ano: 1997,
    gancho: "Un político de Nueva Guinea le hizo una pregunta en una playa. Tardó veinticinco años en contestarla.",
    porQue: "Responde a la mayor pregunta de la historia —por qué unos pueblos conquistaron a otros— sin recurrir ni una vez a la inteligencia o la raza.",
    minutos: 25.6,
    capitulos: [
      { titulo: "Salida: una playa de Nueva Guinea, 1972", minutos: 5.2 },
      { titulo: "Primera parada: catorce animales de ciento cuarenta y ocho", minutos: 5.1 },
      { titulo: "Segunda parada: el eje que va de este a oeste", minutos: 5.1 },
      { titulo: "Tercera parada: Cajamarca, 16 de noviembre de 1532", minutos: 5.1 },
      { titulo: "Destino: lo que la geografía no explica", minutos: 5.2 },
    ],
  },
  {
    id: "diario-ana-frank",
    titulo: "Diario de Ana Frank",
    autor: "Ana Frank",
    ano: 1947,
    gancho: "Se lo regalaron por su cumpleaños, tres semanas antes de esconderse. Escribió en él veinticinco meses.",
    porQue: "Es el testimonio más leído del Holocausto porque no habla del Holocausto: habla de una adolescente discutiendo con su madre en un piso donde no se puede hacer ruido.",
    minutos: 25.9,
    capitulos: [
      { titulo: "Salida: un cuaderno de cuadros rojos", minutos: 5.2 },
      { titulo: "Primera parada: cincuenta metros cuadrados y ocho personas", minutos: 5.2 },
      { titulo: "Segunda parada: la radio de Londres que la volvió escritora", minutos: 5 },
      { titulo: "Tercera parada: lo que su padre quitó", minutos: 5.2 },
      { titulo: "Destino: la frase que todo el mundo cita mal", minutos: 5.3 },
    ],
  },
  {
    id: "canones-agosto",
    titulo: "Los cañones de agosto",
    autor: "Barbara Tuchman",
    ano: 1962,
    gancho: "Un solo mes de 1914 contado en quinientas páginas. Kennedy lo leyó y lo repartió entre su gabinete justo antes de la crisis de los misiles de Cuba.",
    porQue: "Es el mejor libro que existe sobre cómo unos hombres razonables, con buenos planes, meten a un continente entero en una catástrofe en treinta días.",
    minutos: 21.3,
    capitulos: [
      { titulo: "Nueve reyes a caballo", minutos: 4.3 },
      { titulo: "El plan de un hombre muerto", minutos: 4.2 },
      { titulo: "Bélgica", minutos: 4.2 },
      { titulo: "El día más sangriento de Francia", minutos: 4.3 },
      { titulo: "El despacho de Kennedy", minutos: 4.4 },
    ],
  },
  {
    id: "tatuador",
    titulo: "El tatuador de Auschwitz",
    autor: "Heather Morris",
    ano: 2018,
    gancho: "Un hombre de ochenta y siete años que llevaba cincuenta callado, porque temía que si contaba lo que hizo en Auschwitz lo tomaran por colaborador.",
    porQue: "Porque ha vendido más de ocho millones de ejemplares y es, para mucha gente, su única idea de cómo era Auschwitz. Y porque el propio Museo de Auschwitz publicó un informe enumerando lo que tiene de falso.",
    minutos: 20.9,
    capitulos: [
      { titulo: "El número 32407", minutos: 4.3 },
      { titulo: "El hombre que marcaba brazos", minutos: 4.1 },
      { titulo: "34902", minutos: 4.1 },
      { titulo: "Los diamantes en el dobladillo", minutos: 4.1 },
      { titulo: "Melbourne, 2003", minutos: 4.4 },
    ],
  },
  {
    id: "guerra-civil-thomas",
    titulo: "La guerra civil española",
    autor: "Hugh Thomas",
    ano: 1961,
    gancho: "Un inglés de veintinueve años escribió la primera historia completa de la guerra de España. En España estuvo prohibida y entró de contrabando en maletas.",
    porQue: "Durante quince años fue el único libro donde un español podía leer lo que había pasado en su propio país. Hoy está superado en casi todo, y sigue siendo el mejor sitio para entender la guerra entera de una vez.",
    minutos: 23.4,
    capitulos: [
      { titulo: "Un funcionario que dimite por Suez", minutos: 4.9 },
      { titulo: "El 17 de julio de 1936", minutos: 4.7 },
      { titulo: "El Comité de No Intervención, Londres", minutos: 4.7 },
      { titulo: "El Ebro", minutos: 4.5 },
      { titulo: "Ruedo Ibérico, París, 1962", minutos: 4.6 },
    ],
  },
  {
    id: "auschwitz-rees",
    titulo: "Auschwitz: los nazis y la solución final",
    autor: "Laurence Rees",
    ano: 2005,
    gancho: "En mayo de 1940, el sitio era un cuartel abandonado en un pueblo polaco de doce mil habitantes y estaba pensado para presos políticos polacos. Nadie que estuviera allí aquel día había planeado lo que vendría después, y ese es exactamente el argumento del libro.",
    porQue: "Porque explica, paso a paso y con fechas, cómo se llegó hasta allí sin que exista una sola orden firmada; y porque corrige de raíz las dos cosas que casi todo el mundo cree: la cifra de la placa y la idea de que Auschwitz es donde murió la mayoría.",
    minutos: 26.9,
    capitulos: [
      { titulo: "Un cuartel de artillería en un pueblo polaco", minutos: 5.4 },
      { titulo: "Nadie encontró la orden firmada", minutos: 5.4 },
      { titulo: "La cifra de la placa", minutos: 5.3 },
      { titulo: "Los que intentaron pararlo", minutos: 5.3 },
      { titulo: "El contable que se sentó delante de la cámara", minutos: 5.5 },
    ],
  },
  {
    id: "postguerra",
    titulo: "Postguerra",
    autor: "Tony Judt",
    ano: 2005,
    gancho: "Europa en 1945 era un continente de escombros, hambre y treinta millones de muertos. Cómo salió de ahí es la mejor historia que se ha escrito de nuestro propio siglo.",
    porQue: "Explica de dónde salieron el estado del bienestar, la Unión Europea y la Transición española, y por qué nada de eso era inevitable. Y termina con la idea más incómoda del libro: que Europa se reconstruyó sobre un acuerdo de no recordar.",
    minutos: 24.3,
    capitulos: [
      { titulo: "El año cero", minutos: 5.1 },
      { titulo: "Los treinta años que parecieron normales", minutos: 5.6 },
      { titulo: "La mitad que se quedó al otro lado", minutos: 4.3 },
      { titulo: "1968, 1973 y la vuelta del sur", minutos: 4.6 },
      { titulo: "1989 y la deuda con los muertos", minutos: 4.8 },
    ],
  },
  {
    id: "homo-sovieticus",
    titulo: "El fin del Homo Sovieticus",
    autor: "Svetlana Aleksiévich",
    ano: 2013,
    gancho: "Veinte años grabando a gente corriente del imperio que se cayó. Le dieron el Nobel por ello, y también la llevaron a juicio por lo mismo: por lo que hace con las cintas cuando se sienta a escribir.",
    porQue: "Porque es el mejor retrato que existe de lo que le pasa por dentro a un país cuando se le acaba el mundo. Y porque su título original no dice lo que dice el español: no habla de un final, habla de ropa usada que alguien se ha vuelto a poner.",
    minutos: 25.9,
    capitulos: [
      { titulo: "Un mariscal se ahorca en su despacho del Kremlin", minutos: 5.1 },
      { titulo: "Cien horas de grabación para tres páginas", minutos: 5.2 },
      { titulo: "La libertad resultó ser el salchichón", minutos: 5.2 },
      { titulo: "El juicio de Minsk", minutos: 5.1 },
      { titulo: "Tiempo de segunda mano", minutos: 5.2 },
    ],
  },
  {
    id: "imperiofobia",
    titulo: "Imperiofobia y leyenda negra",
    autor: "María Elvira Roca Barea",
    ano: 2016,
    gancho: "Sostiene que España es el único imperio de la historia que se creyó la propaganda de sus enemigos. Vendió cientos de miles de ejemplares y los historiadores profesionales lo destrozaron.",
    porQue: "Porque lleva razón en muchos datos concretos que casi nadie conoce y usa el mismo método que denuncia. Leerlo bien enseña a la vez historia de España y algo más útil: cómo se fabrica el relato que un país se cuenta de sí mismo.",
    minutos: 24.6,
    capitulos: [
      { titulo: "Un panfleto impreso en Delft", minutos: 5 },
      { titulo: "Los datos que casi nadie conoce", minutos: 5.1 },
      { titulo: "Lo que le contestaron los historiadores", minutos: 4.8 },
      { titulo: "Cómo se fabrica el relato de un país", minutos: 4.9 },
      { titulo: "Qué hacer con un libro así", minutos: 4.8 },
    ],
  },
  {
    id: "etica-amador",
    titulo: "Ética para Amador",
    autor: "Fernando Savater",
    ano: 1991,
    gancho: "Un catedrático de filosofía le escribe a su hijo de quince años para explicarle por qué no piensa darle ni una sola norma de conducta.",
    porQue: "Es el libro de filosofía más leído en español del último medio siglo, y su tesis central sigue siendo la más incómoda: portarse bien es un asunto de egoísmo bien entendido.",
    minutos: 22,
    capitulos: [
      { titulo: "Una carta a un hijo de quince años", minutos: 4.4 },
      { titulo: "Las termitas no pueden elegir", minutos: 4.4 },
      { titulo: "Haz lo que quieras", minutos: 4.4 },
      { titulo: "Ponte en su lugar", minutos: 4.3 },
      { titulo: "Lo que respondió Amador", minutos: 4.5 },
    ],
  },
  {
    id: "etica-nicomaco",
    titulo: "Ética a Nicómaco",
    autor: "Aristóteles",
    ano: -340,
    gancho: "El primer manual de cómo vivir. No pregunta qué debes hacer, sino en quién te estás convirtiendo cada vez que lo haces.",
    porQue: "Es el origen de casi todo lo que hoy se dice sobre hábitos, carácter y amistad, y lo dice mejor que sus herederos. Leerlo entero enseña además a distinguir lo que sobrevive de un clásico de lo que caducó con su autor.",
    minutos: 25,
    capitulos: [
      { titulo: "Una escuela a las afueras de Atenas", minutos: 5.2 },
      { titulo: "El término medio no es la mitad", minutos: 5 },
      { titulo: "Se aprende tocando la cítara", minutos: 4.7 },
      { titulo: "Los amigos que hacen falta", minutos: 5.3 },
      { titulo: "La vida que se elige por sí misma", minutos: 4.8 },
    ],
  },
  {
    id: "contrato-social",
    titulo: "El contrato social",
    autor: "Jean-Jacques Rousseau",
    ano: 1762,
    gancho: "Lo quemaron en Ginebra y en París el mismo año de publicarse, y su autor tuvo que huir de tres países. Treinta años después, los revolucionarios franceses llevaron sus restos al Panteón en volandas.",
    porQue: "Porque de aquí sale la idea de que la ley solo obliga si la hemos hecho nosotros, que es el fundamento de cualquier democracia. Y porque casi todo lo que se le atribuye —el buen salvaje, la vuelta a la naturaleza, el gobierno de la mayoría— no está en el libro.",
    minutos: 26.1,
    capitulos: [
      { titulo: "Una frase que todo el mundo cita a medias", minutos: 5.1 },
      { titulo: "El buen salvaje que nunca escribió", minutos: 5.4 },
      { titulo: "La voluntad general no es la mayoría", minutos: 5.2 },
      { titulo: "El pueblo inglés cree ser libre", minutos: 5.2 },
      { titulo: "Los cinco niños del hospicio", minutos: 5.2 },
    ],
  },
  {
    id: "mas-alla-bien-mal",
    titulo: "Más allá del bien y del mal",
    autor: "Friedrich Nietzsche",
    ano: 1886,
    gancho: "Lo pagó de su bolsillo, se imprimieron seiscientos ejemplares y en el primer año vendió poco más de cien. Cuarenta años después, su hermana recibía a Hitler en el archivo donde guardaba sus papeles, con un libro suyo que él nunca escribió.",
    porQue: "Porque es el Nietzsche argumentado, el que explica en prosa lo que Zaratustra decía en parábolas. Y porque el título no significa lo que casi todo el mundo cree que significa: no es una licencia para hacer lo que a uno le dé la gana.",
    minutos: 27.5,
    capitulos: [
      { titulo: "Seiscientos ejemplares pagados de su bolsillo", minutos: 5.3 },
      { titulo: "El filósofo también tiene un cuerpo", minutos: 5.5 },
      { titulo: "Dos maneras de decir bueno", minutos: 5.7 },
      { titulo: "Lo que no se puede lavar", minutos: 5.4 },
      { titulo: "El archivo de Weimar", minutos: 5.6 },
    ],
  },
  {
    id: "existencialismo-humanismo",
    titulo: "El existencialismo es un humanismo",
    autor: "Jean-Paul Sartre",
    ano: 1946,
    gancho: "El texto filosófico más leído del siglo XX es la transcripción de una conferencia que su autor dio sin notas, en una sala donde la gente se desmayaba, y de cuya publicación se arrepintió el resto de su vida.",
    porQue: "Porque de aquí salen las tres frases que todo el mundo cita sobre la libertad. Y porque leerlo entero enseña algo que las frases sueltas ocultan: que no es una filosofía permisiva, sino la más exigente que hay en el estante.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Una sala rota en la rue Jean-Goujon", minutos: 5 },
      { titulo: "Un cortapapeles y un Dios que no está", minutos: 5.1 },
      { titulo: "El chico que no sabía si irse a Londres", minutos: 5.1 },
      { titulo: "La carta que le mandó Heidegger", minutos: 5.1 },
      { titulo: "Lo que Sartre dejó de creer", minutos: 5.2 },
    ],
  },
  {
    id: "ensayos-montaigne",
    titulo: "Ensayos",
    autor: "Michel de Montaigne",
    ano: 1580,
    gancho: "Se encerró en una torre a los treinta y ocho años para escribir sobre el único asunto que conocía de primera mano: él mismo. Inventó de paso un género entero.",
    porQue: "Es el primer libro moderno y sigue siendo el más honrado. Enseña un hábito que no caduca: preguntarle a cada cosa que uno cree si la creería igual habiendo nacido cuarenta leguas más allá.",
    minutos: 25,
    capitulos: [
      { titulo: "Una torre con frases en el techo", minutos: 5 },
      { titulo: "El hombre que se puso a sí mismo de tema", minutos: 5 },
      { titulo: "Contra la crueldad", minutos: 5 },
      { titulo: "La caída del caballo", minutos: 5 },
      { titulo: "Lo que hizo con los que vinieron después", minutos: 5.1 },
    ],
  },
  {
    id: "universo-cascara",
    titulo: "El universo en una cáscara de nuez",
    autor: "Stephen Hawking",
    ano: 2001,
    gancho: "Escribió la continuación de su libro más famoso porque le habían dicho que el primero no lo entendía nadie. El segundo tampoco es fácil, y explica cosas más raras.",
    porQue: "Porque su predicción más importante —que los agujeros negros se evaporan— sigue sin haberse observado, y eso explica por qué nunca le dieron el Nobel.",
    minutos: 21.8,
    capitulos: [
      { titulo: "Dos años de vida", minutos: 4.4 },
      { titulo: "La cáscara de nuez", minutos: 4.5 },
      { titulo: "Los agujeros negros no son negros", minutos: 4.4 },
      { titulo: "La apuesta de la enciclopedia", minutos: 4.4 },
      { titulo: "Lo que no se ha visto", minutos: 4.3 },
    ],
  },
  {
    id: "ultimos-dinosaurios",
    titulo: "Los últimos días de los dinosaurios",
    autor: "Riley Black",
    ano: 2022,
    gancho: "La primera hora después del impacto, contada minuto a minuto. El asteroide no mató a los dinosaurios: los mató lo que pasó en los meses siguientes.",
    porQue: "Reconstruye el peor día de la historia de la vida en la Tierra con el detalle de una crónica, y luego explica de dónde sale cada dato de esa crónica.",
    minutos: 21.7,
    capitulos: [
      { titulo: "La última tarde de Hell Creek", minutos: 4.3 },
      { titulo: "La hora del cielo en llamas", minutos: 4.4 },
      { titulo: "El invierno sin sol", minutos: 4.3 },
      { titulo: "Los que sobrevivieron en un agujero", minutos: 4.3 },
      { titulo: "Un millón de años después", minutos: 4.4 },
    ],
  },
  {
    id: "einstein",
    titulo: "Einstein: su vida y su universo",
    autor: "Walter Isaacson",
    ano: 2007,
    gancho: "Un funcionario de patentes de veintiséis años publica en un año cuatro artículos. Tres de ellos cambian la física. Y no, nunca suspendió matemáticas.",
    porQue: "Es la biografía que usó por primera vez sus cartas privadas, y el retrato que sale no es el del abuelo simpático de los pósters.",
    minutos: 21.7,
    capitulos: [
      { titulo: "La brújula", minutos: 4.4 },
      { titulo: "Montar sobre un rayo de luz", minutos: 4.5 },
      { titulo: "La oficina de patentes", minutos: 4.3 },
      { titulo: "El eclipse de 1919", minutos: 4.2 },
      { titulo: "Princeton", minutos: 4.4 },
    ],
  },
  {
    id: "musica-primos",
    titulo: "La música de los números primos",
    autor: "Marcus du Sautoy",
    ano: 2003,
    gancho: "En 1859 un alemán tímido escribió ocho páginas sobre los números primos. Ciento sesenta y seis años después, nadie ha conseguido demostrar la frase que dejó a medias.",
    porQue: "Porque es la mejor puerta de entrada al problema abierto más famoso de las matemáticas, y porque exagera en el único capítulo que todo el mundo cita: el de la criptografía.",
    minutos: 22.4,
    capitulos: [
      { titulo: "La conjetura de un chico de quince años", minutos: 4.5 },
      { titulo: "Las ocho páginas de Riemann", minutos: 4.6 },
      { titulo: "Todos los ceros en la misma recta", minutos: 4.4 },
      { titulo: "Los cazadores de ceros", minutos: 4.5 },
      { titulo: "El millón de dólares sigue en el banco", minutos: 4.5 },
    ],
  },
  {
    id: "universo-mano",
    titulo: "El universo en tu mano",
    autor: "Christophe Galfard",
    ano: 2015,
    gancho: "Un doctorando de Stephen Hawking se propuso contar toda la física del siglo veinte sin una sola ecuación, y llevándote a ti de excursión hasta el borde de lo que se sabe.",
    porQue: "Porque es el mejor viaje guiado por el universo que se ha escrito en este siglo, y porque en los tres últimos capítulos te lleva a sitios donde no hay ni una sola prueba experimental sin avisarte del todo.",
    minutos: 21.7,
    capitulos: [
      { titulo: "Tumbado en una playa", minutos: 4.1 },
      { titulo: "La fábrica de los átomos", minutos: 4.3 },
      { titulo: "El ruido que nadie conseguía quitar", minutos: 4.5 },
      { titulo: "Cuando nadie mira", minutos: 4.6 },
      { titulo: "El muro de Planck", minutos: 4.2 },
    ],
  },
  {
    id: "pulgar-panda",
    titulo: "El pulgar del panda",
    autor: "Stephen Jay Gould",
    ano: 1980,
    gancho: "La mejor prueba de la evolución no son los animales perfectos: son las chapuzas. Un hueso de la muñeca convertido en dedo para pelar bambú.",
    porQue: "Es la respuesta más elegante que existe a quien dice que el ojo es demasiado complejo para haber evolucionado. Y enseña a discutir: el autor pasó la vida peleándose con otro biólogo de esta misma biblioteca, y los dos tenían parte de razón.",
    minutos: 25.2,
    capitulos: [
      { titulo: "Un sexto dedo que no es un dedo", minutos: 5.2 },
      { titulo: "Las rocas que decían la verdad", minutos: 5 },
      { titulo: "Las enjutas de San Marcos", minutos: 4.9 },
      { titulo: "El que mide también tiene sesgos", minutos: 5.2 },
      { titulo: "La pelea con el gen egoísta", minutos: 5 },
    ],
  },
  {
    id: "cuchara-menguante",
    titulo: "La cuchara menguante",
    autor: "Sam Kean",
    ano: 2010,
    gancho: "Una broma de laboratorio: dar el té a una visita con una cucharilla que se derrite al removerlo. El metal existe, se llama galio, y da título al libro que convirtió la tabla periódica en un anecdotario.",
    porQue: "Porque hay diez historias aquí que se recuerdan para siempre y ninguna se aprende en el colegio. Y porque conviene saber qué clase de libro es: no explica cómo funciona la tabla periódica, y su anécdota más famosa está contada en la versión bonita y no en la verdadera.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Una cuchara que se derrite en el té", minutos: 5.1 },
      { titulo: "El hombre que corrigió una medición sin ver el metal", minutos: 5.1 },
      { titulo: "El oro que sirvió para tapar baches", minutos: 5 },
      { titulo: "Las chicas que se pintaban los dientes", minutos: 5.1 },
      { titulo: "El hueco número cuarenta y tres", minutos: 5.2 },
    ],
  },
  {
    id: "camino-artista",
    titulo: "El camino del artista",
    autor: "Julia Cameron",
    ano: 1992,
    gancho: "Dejó de beber a los treinta años convencida de que el alcohol era lo que la hacía escribir. Descubrió que era al revés y montó un curso de doce semanas.",
    porQue: "Es el libro que ha desbloqueado a más gente creativa que ningún otro, y su herramienta principal cabe en tres folios y un bolígrafo.",
    minutos: 21.3,
    capitulos: [
      { titulo: "El día que dejó de beber", minutos: 4.3 },
      { titulo: "Tres páginas a mano", minutos: 4.4 },
      { titulo: "La cita con el artista", minutos: 4.3 },
      { titulo: "Los artistas en la sombra", minutos: 4.1 },
      { titulo: "Salta y aparecerá la red", minutos: 4.2 },
    ],
  },
  {
    id: "arte-sin-hombres",
    titulo: "Historia del arte sin hombres",
    autor: "Katy Hessel",
    ano: 2022,
    gancho: "En una feria de arte de Londres con miles de obras no había ni una sola de una mujer. La que se dio cuenta tenía veintiún años y decidió escribir el otro libro.",
    porQue: "Es la respuesta directa al manual de Gombrich, y no va de opinar: va de enseñar los mecanismos concretos por los que media historia del arte desapareció.",
    minutos: 22,
    capitulos: [
      { titulo: "Una feria sin una sola mujer", minutos: 4.4 },
      { titulo: "El juicio de Artemisia", minutos: 4.4 },
      { titulo: "Las dos que solo están en el cuadro", minutos: 4.3 },
      { titulo: "La abstracción llegó antes", minutos: 4.6 },
      { titulo: "¿Hay que estar desnuda?", minutos: 4.3 },
    ],
  },
  {
    id: "vida-dali",
    titulo: "La vida secreta de Salvador Dalí",
    autor: "Salvador Dalí",
    ano: 1942,
    gancho: "Sus padres le pusieron el nombre de un hermano muerto nueve meses antes de nacer él. A los cinco años lo llevaron a su tumba y le dijeron que era su reencarnación.",
    porQue: "Es la autobiografía más mentirosa que se ha escrito y sigue siendo imprescindible, porque la mentira es exactamente el objeto de estudio.",
    minutos: 21.6,
    capitulos: [
      { titulo: "La tumba del hermano", minutos: 4.5 },
      { titulo: "La Residencia", minutos: 4.2 },
      { titulo: "Gala", minutos: 4.4 },
      { titulo: "Ávida Dollars", minutos: 4.4 },
      { titulo: "La cripta de Figueres", minutos: 4.2 },
    ],
  },
  {
    id: "diarios-frida",
    titulo: "El diario de Frida Kahlo",
    autor: "Frida Kahlo",
    ano: 1995,
    gancho: "Ciento setenta páginas que nunca quiso que se publicaran. Se editaron en facsímil cuarenta y un años después de su muerte, con las manchas incluidas.",
    porQue: "Porque es el documento más íntimo del arte del siglo XX, y porque leerlo obliga a preguntarse qué derecho tiene nadie a leer el cuaderno privado de una muerta.",
    minutos: 21.6,
    capitulos: [
      { titulo: "El pasamanos", minutos: 4.4 },
      { titulo: "El espejo del dosel", minutos: 4.3 },
      { titulo: "Diego", minutos: 4.4 },
      { titulo: "Pies para qué los quiero", minutos: 4.3 },
      { titulo: "La cama en la galería", minutos: 4.1 },
    ],
  },
  {
    id: "van-gogh-cartas",
    titulo: "Cartas a Theo",
    autor: "Vincent van Gogh",
    ano: 1914,
    gancho: "Pintó unas dos mil obras en diez años y solo se le documenta una venta. Su hermano le pagó cada tubo de pintura.",
    porQue: "Las cartas desmontan el mito del loco que pintaba por instinto: era un lector voraz que razonaba cada color. Y existen porque una viuda de veintiocho años decidió que existieran.",
    minutos: 26.6,
    capitulos: [
      { titulo: "El evangelista despedido de las minas", minutos: 5.2 },
      { titulo: "Ciento cincuenta francos al mes", minutos: 5.5 },
      { titulo: "Por qué este rojo va contra este verde", minutos: 5.2 },
      { titulo: "La oreja de la que no habla", minutos: 5.3 },
      { titulo: "La viuda que inventó a Van Gogh", minutos: 5.3 },
    ],
  },
  {
    id: "magia-crear",
    titulo: "La magia de crear",
    autor: "Elizabeth Gilbert",
    ano: 2015,
    gancho: "Sostiene que las ideas son criaturas conscientes que van buscando un colaborador humano, y que si tú no la coges se marcha a otra casa. Y cuenta el caso concreto en el que dice que le pasó, con nombre y apellido de la escritora que la recibió.",
    porQue: "Porque su consejo central va contra todo lo que dice el género: no dejes el trabajo, no le pidas a tu arte que te pague el alquiler. Y porque la autora acabó haciendo con un libro suyo exactamente lo contrario de lo que este libro predica.",
    minutos: 27.5,
    capitulos: [
      { titulo: "Una novela que se fue a otra casa", minutos: 6 },
      { titulo: "Tener un genio en vez de serlo", minutos: 5.3 },
      { titulo: "No le pidas a tu arte que te pague el alquiler", minutos: 5.5 },
      { titulo: "El problema de escribirlo desde arriba", minutos: 5.3 },
      { titulo: "El libro que retiró", minutos: 5.4 },
    ],
  },
  {
    id: "pajaro-a-pajaro",
    titulo: "Pájaro a pájaro",
    autor: "Anne Lamott",
    ano: 1994,
    gancho: "Un niño de diez años lleva tres meses con un trabajo sobre pájaros y lo tiene que entregar mañana. Está paralizado. Su padre se sienta a su lado.",
    porQue: "No enseña a escribir bien: enseña a escribir mal a propósito, que es el requisito previo que nadie cuenta. Y dice en voz alta lo que ningún libro del género dice: que publicar no arregla nada.",
    minutos: 22.7,
    capitulos: [
      { titulo: "La mesa del comedor, en Marin County", minutos: 4.4 },
      { titulo: "El primer borrador de mierda", minutos: 4.5 },
      { titulo: "La emisora que suena dentro", minutos: 4.6 },
      { titulo: "El marco de un palmo", minutos: 4.7 },
      { titulo: "El día que sale el libro", minutos: 4.5 },
    ],
  },
  {
    id: "vidas-vasari",
    titulo: "Las vidas de los más excelentes pintores, escultores y arquitectos",
    autor: "Giorgio Vasari",
    ano: 1550,
    gancho: "Casi todo lo que crees saber sobre los artistas del Renacimiento lo escribió un pintor de Arezzo que conocía a la mitad de ellos.",
    porQue: "Es el primer libro de historia del arte que se escribió, y sigue siendo la fuente de casi todas las anécdotas que circulan sobre Giotto, Leonardo o Miguel Ángel. También es donde nacieron algunos de los errores que todavía repetimos.",
    minutos: 23.8,
    capitulos: [
      { titulo: "Una cena en casa del cardenal", minutos: 4.8 },
      { titulo: "El niño que dibujaba ovejas", minutos: 4.8 },
      { titulo: "Las puertas del Paraíso", minutos: 4.7 },
      { titulo: "El funeral de San Lorenzo", minutos: 4.8 },
      { titulo: "El muro de la Sala de los Quinientos", minutos: 4.7 },
    ],
  },
  {
    id: "espiritual-arte",
    titulo: "De lo espiritual en el arte",
    autor: "Vasili Kandinsky",
    ano: 1911,
    gancho: "El libro con el que un pintor se dio permiso para dejar de pintar cosas. Su teoría del color es casi toda falsa y aun así cambió lo que se cuelga en las paredes.",
    porQue: "Porque explica de dónde salió el arte abstracto, que es lo que más incomoda al visitante de un museo. Y enseña una manera concreta de mirar un cuadro que no representa nada, que es dejar de preguntar qué es.",
    minutos: 24,
    capitulos: [
      { titulo: "Un cuadro apoyado del revés", minutos: 4.9 },
      { titulo: "El amarillo suena a trompeta", minutos: 4.9 },
      { titulo: "La necesidad interior", minutos: 4.8 },
      { titulo: "La mujer que llegó cuatro años antes", minutos: 4.8 },
      { titulo: "Del Bauhaus a la pared del salón", minutos: 4.7 },
    ],
  },
  {
    id: "reproductibilidad",
    titulo: "La obra de arte en la época de su reproductibilidad técnica",
    autor: "Walter Benjamin",
    ano: 1936,
    gancho: "Un refugiado alemán sin trabajo escribió en un café de París por qué una foto de un cuadro no es el cuadro. Cuatro años después murió en la frontera española.",
    porQue: "Es el ensayo del que salió todo lo que se dice hoy sobre imágenes, copias y originales. Y casi nadie lo lee: se citan cuatro frases suyas, casi siempre al revés de lo que él quería decir.",
    minutos: 22.5,
    capitulos: [
      { titulo: "El Instituto en el exilio", minutos: 4.5 },
      { titulo: "El aura", minutos: 4.8 },
      { titulo: "La sala de montaje", minutos: 4.6 },
      { titulo: "El estadio de Núremberg", minutos: 4.2 },
      { titulo: "Portbou, 26 de septiembre de 1940", minutos: 4.3 },
    ],
  },
  {
    id: "heroe-mil-caras",
    titulo: "El héroe de las mil caras",
    autor: "Joseph Campbell",
    ano: 1949,
    gancho: "Un hombre sin doctorado, que se pasó cinco años sin trabajo leyendo nueve horas al día en una cabaña, escribió el esquema con el que se construyen hoy la mitad de las películas de Hollywood.",
    porQue: "Porque su estructura funciona sorprendentemente bien para escribir historias y es bastante mala como descripción de la mitología del mundo, y casi nadie distingue las dos cosas.",
    minutos: 22,
    capitulos: [
      { titulo: "Cinco años leyendo en una cabaña", minutos: 4.5 },
      { titulo: "El monomito", minutos: 4.2 },
      { titulo: "El rancho Skywalker, 1983", minutos: 4.5 },
      { titulo: "Los mitos que no encajan", minutos: 4.6 },
      { titulo: "La diosa y la tentadora", minutos: 4.1 },
    ],
  },
  {
    id: "el-elemento",
    titulo: "El elemento",
    autor: "Ken Robinson",
    ano: 2009,
    gancho: "La charla más vista de la historia de TED se apoya en una estadística que la NASA nunca hizo. Y el argumento, curiosamente, aguanta igual sin ella.",
    porQue: "Porque es el libro que convenció a media docena de generaciones de que el colegio les había escondido algo. Vale la pena separar lo que Robinson demostró de lo que solo contó bien, porque las dos cosas están mezcladas y la segunda es la que más se repite.",
    minutos: 25,
    capitulos: [
      { titulo: "Una niña que no paraba quieta", minutos: 5 },
      { titulo: "Diecinueve minutos en Monterrey", minutos: 5 },
      { titulo: "El test que la NASA nunca hizo", minutos: 5.1 },
      { titulo: "La escuela que dicen que es una fábrica", minutos: 4.9 },
      { titulo: "Lo que aguanta cuando le quitas las cifras", minutos: 5 },
    ],
  },
  {
    id: "mujercitas",
    titulo: "Mujercitas",
    autor: "Louisa May Alcott",
    ano: 1868,
    gancho: "Le encargaron un libro para chicas. Escribió en su diario que no le apetecía nada, que nunca le habían gustado las chicas y que no conocía a ninguna aparte de sus hermanas. Lo terminó en diez semanas.",
    porQue: "Porque el libro que enseñó a varias generaciones de mujeres que se podía querer otra cosa lo escribió alguien que estaba negociando, capítulo a capítulo, con lo que su editor le dejaba escribir.",
    minutos: 22.1,
    capitulos: [
      { titulo: "Fruitlands, siete meses", minutos: 4.5 },
      { titulo: "Un libro para chicas", minutos: 4.2 },
      { titulo: "No voy a casar a Jo con Laurie", minutos: 4.4 },
      { titulo: "La casa de Concord", minutos: 4.6 },
      { titulo: "El escritorio entre dos ventanas", minutos: 4.4 },
    ],
  },
  {
    id: "cuentos-poe",
    titulo: "Cuentos de Edgar Allan Poe",
    autor: "Edgar Allan Poe",
    ano: 1845,
    gancho: "Inventó el relato de detectives, fijó las reglas del cuento moderno y escribió el poema más famoso de su país. Cobró nueve dólares por él y murió nueve años después, delirando, con la ropa de otro hombre.",
    porQue: "Porque casi todo lo que la gente cree saber de él lo escribió el hombre que lo odiaba, y porque su fama de autor de terror esconde que inventó dos géneros enteros.",
    minutos: 22,
    capitulos: [
      { titulo: "Un huérfano en Richmond", minutos: 4.1 },
      { titulo: "El hombre del tomahawk", minutos: 4.5 },
      { titulo: "El corazón debajo del suelo", minutos: 4.5 },
      { titulo: "El cuervo y los nueve dólares", minutos: 4.4 },
      { titulo: "Baltimore, 3 de octubre de 1849", minutos: 4.5 },
    ],
  },
  {
    id: "elegancia-erizo",
    titulo: "La elegancia del erizo",
    autor: "Muriel Barbery",
    ano: 2006,
    gancho: "Una portera de cincuenta y cuatro años finge ser tonta durante veintisiete años para que la dejen en paz, mientras lee a Tolstói y a Husserl en el cuarto de atrás.",
    porQue: "Porque vendió millones de ejemplares por el boca a boca y porque su idea de fondo —que la cultura es la verdadera aristocracia— es a la vez lo que lo hace emocionante y lo que lo hace tramposo.",
    minutos: 21.8,
    capitulos: [
      { titulo: "La portera del número 7", minutos: 4.2 },
      { titulo: "Una niña con fecha", minutos: 4.4 },
      { titulo: "Todas las familias felices se parecen", minutos: 4.6 },
      { titulo: "La furgoneta de la tintorería", minutos: 4.3 },
      { titulo: "Camelias sobre el musgo", minutos: 4.4 },
    ],
  },
  {
    id: "el-tunel",
    titulo: "El túnel",
    autor: "Ernesto Sabato",
    ano: 1948,
    gancho: "Lo escribió un doctor en física que había trabajado en el laboratorio Curie y que a los treinta y cuatro años abandonó la ciencia para siempre. Es la mejor novela en español sobre un razonamiento impecable que termina en un crimen.",
    porQue: "Porque en ciento cincuenta páginas enseña algo que no se aprende de otra manera: cómo se construye una certeza absoluta a partir de nada, paso a paso, sin que ninguno de los pasos sea ilógico. Y porque casi todo el mundo la lee olvidando quién la está contando.",
    minutos: 26.2,
    capitulos: [
      { titulo: "El primer párrafo dice quién y a quién", minutos: 5.3 },
      { titulo: "Una ventanita en la esquina de un cuadro", minutos: 5.2 },
      { titulo: "La cadena de razonamientos", minutos: 5.2 },
      { titulo: "Todo lo que sabemos de María", minutos: 5.3 },
      { titulo: "Dos túneles paralelos", minutos: 5.2 },
    ],
  },
  {
    id: "renglones-torcidos",
    titulo: "Los renglones torcidos de Dios",
    autor: "Torcuato Luca de Tena",
    ano: 1979,
    gancho: "Para escribirla, el director de un periódico nacional se hizo ingresar en un psiquiátrico durante dieciocho días. Solo el director del centro sabía que no estaba enfermo, y ni siquiera él sabía cómo iba a salir de allí.",
    porQue: "Porque plantea la pregunta más incómoda que existe: cómo demostrarías que estás cuerdo si nadie te creyera. Y porque el experimento científico que hizo esa misma pregunta seis años antes acabó, cuarenta años después, resultando bastante menos limpio de lo que decía.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Dieciocho días de ingreso voluntario", minutos: 5.3 },
      { titulo: "Una detective que dice ser detective", minutos: 5 },
      { titulo: "El experimento que se le adelantó seis años", minutos: 4.9 },
      { titulo: "Los internos", minutos: 5.2 },
      { titulo: "Renglones torcidos", minutos: 5.2 },
    ],
  },
  {
    id: "cerebro-del-nino",
    titulo: "El cerebro del niño",
    autor: "Siegel y Payne Bryson",
    ano: 2011,
    gancho: "Doce estrategias para criar, todas envueltas en neurociencia. Los consejos son buenos y llevan décadas funcionando. La neurociencia, en cambio, está ahí sobre todo para que te los creas.",
    porQue: "Porque es el manual de crianza más vendido de los últimos quince años y merece que alguien separe lo que está probado de lo que está decorado. Y porque hay un experimento de 1975, que el libro apenas menciona, que demuestra su tesis mejor que todas sus resonancias juntas.",
    minutos: 26.2,
    capitulos: [
      { titulo: "Una rabieta en el asiento de atrás", minutos: 5.4 },
      { titulo: "El río entre el caos y la rigidez", minutos: 5.4 },
      { titulo: "Ponle nombre para domarlo", minutos: 5.3 },
      { titulo: "El encanto de una resonancia magnética", minutos: 5.1 },
      { titulo: "La cara que deja de responder", minutos: 5 },
    ],
  },
  {
    id: "cosas-buenas",
    titulo: "Cómo hacer que te pasen cosas buenas",
    autor: "Marian Rojas Estapé",
    ano: 2018,
    gancho: "Es probablemente el libro de divulgación más vendido en España en lo que va de siglo, y repite en cada capítulo una frase que es falsa tal y como está escrita.",
    porQue: "Porque su capítulo sobre el estrés crónico está bien y es útil, y porque su neurociencia de cuatro hormonas es una versión de manual popular que conviene saber leer con distancia.",
    minutos: 21.9,
    capitulos: [
      { titulo: "La hija del psiquiatra", minutos: 4.1 },
      { titulo: "El oso que no está", minutos: 4.7 },
      { titulo: "El circuito de la recompensa", minutos: 4.2 },
      { titulo: "Personas vitamina", minutos: 4.5 },
      { titulo: "La psiquiatra que dice que vayas al psiquiatra", minutos: 4.4 },
    ],
  },
  {
    id: "marte-venus",
    titulo: "Los hombres son de Marte, las mujeres son de Venus",
    autor: "John Gray",
    ano: 1992,
    gancho: "Cincuenta millones de ejemplares vendidos sobre una teoría que la investigación no sostiene. Y aun así, mucha gente dice que le salvó la relación.",
    porQue: "Porque la pregunta buena no es si acierta, sino por qué funciona un libro que se equivoca. Contestarla enseña más sobre parejas que el propio libro, y de paso deja lo que sí está medido, que existe y casi nadie conoce.",
    minutos: 24.2,
    capitulos: [
      { titulo: "Un seminario en California", minutos: 4.3 },
      { titulo: "La cueva, la ola y la goma elástica", minutos: 5.1 },
      { titulo: "Lo que dicen los datos sobre las diferencias", minutos: 4.7 },
      { titulo: "Por qué funciona un libro que se equivoca", minutos: 5.1 },
      { titulo: "El apartamento con cámaras de Seattle", minutos: 5 },
    ],
  },
  {
    id: "intro-psicoanalisis",
    titulo: "Introducción al psicoanálisis",
    autor: "Sigmund Freud",
    ano: 1917,
    gancho: "Veintiocho clases en las que un médico vienés intenta convencer a una sala llena de escépticos de que no somos dueños de nuestra propia cabeza.",
    porQue: "Es Freud explicándose a sí mismo para gente que no sabe nada, y por eso es la puerta de entrada. También es el sitio donde se ve mejor qué se sostiene de todo aquello y qué no.",
    minutos: 22.6,
    capitulos: [
      { titulo: "El anfiteatro de la Universidad de Viena", minutos: 4.6 },
      { titulo: "Los actos fallidos", minutos: 4.5 },
      { titulo: "El taller de los sueños", minutos: 4.4 },
      { titulo: "El diván de Berggasse 19", minutos: 4.5 },
      { titulo: "La casa de Maresfield Gardens", minutos: 4.5 },
    ],
  },
  {
    id: "maneras-de-amar",
    titulo: "Maneras de amar",
    autor: "Levine y Heller",
    ano: 2010,
    gancho: "Las cifras que hoy repite medio internet —la mitad de la gente es segura, un cuarto evitativa, un quinto ansiosa— salen de un cuestionario que dos psicólogos publicaron en un periódico de Denver en 1985 y que los lectores contestaron por correo.",
    porQue: "Porque explica por qué la pareja que te vuelve loco te parece más intensa que la que te trata bien, y porque su vocabulario se ha convertido en un horóscopo de tres casillas que el propio libro no defiende.",
    minutos: 27,
    capitulos: [
      { titulo: "Un cuestionario en un periódico de Denver", minutos: 5.5 },
      { titulo: "Qué hace cada uno cuando tiene miedo", minutos: 5.4 },
      { titulo: "La trampa", minutos: 5.4 },
      { titulo: "Lo que este libro no puede demostrar", minutos: 5.2 },
      { titulo: "Depender bien", minutos: 5.5 },
    ],
  },
  {
    id: "sentirse-bien",
    titulo: "Sentirse bien",
    autor: "David D. Burns",
    ano: 1980,
    gancho: "Es el único libro de autoayuda que se ha probado en ensayos clínicos como si fuera un medicamento. Y salió bien. Lo raro es que su autor acabó publicando datos contra la teoría que lo sostiene.",
    porQue: "Porque es el manual que puso la terapia cognitiva en manos de cualquiera, con un lápiz y una hoja de tres columnas. Y porque su historia enseña algo que casi ningún libro cuenta: que un ejercicio puede funcionar aunque la explicación de por qué funciona sea falsa.",
    minutos: 25.5,
    capitulos: [
      { titulo: "El residente que quería darle la razón a Freud", minutos: 5 },
      { titulo: "Las diez trampas del cuaderno", minutos: 5.1 },
      { titulo: "Tres columnas y un lápiz", minutos: 5.3 },
      { titulo: "Lo que dijeron los ensayos", minutos: 5.2 },
      { titulo: "Lo que queda cuando se cae la teoría", minutos: 4.9 },
    ],
  },
  {
    id: "doctrina-shock",
    titulo: "La doctrina del shock",
    autor: "Naomi Klein",
    ano: 2007,
    gancho: "Su tesis es que las reformas que nadie votaría se aprueban en los días en que la gente está demasiado aturdida para discutirlas. Documenta cuarenta años de ejemplos.",
    porQue: "Es el libro que puso nombre a algo que se ve cada vez que hay una catástrofe. Y es también un caso de estudio perfecto de cómo se lee un libro de tesis fuerte: separando lo que documenta de lo que solo insinúa, que aquí son dos cosas muy distintas.",
    minutos: 25.3,
    capitulos: [
      { titulo: "Un sótano de Montreal", minutos: 4.4 },
      { titulo: "El primer laboratorio fue Chile", minutos: 5.6 },
      { titulo: "Cuando la crisis llega sola", minutos: 5.5 },
      { titulo: "Bagdad, Nueva Orleans y una playa de Sri Lanka", minutos: 5.5 },
      { titulo: "Lo que demuestra y lo que solo insinúa", minutos: 4.3 },
    ],
  },
  {
    id: "millonario-al-lado",
    titulo: "El millonario de al lado",
    autor: "Stanley y Danko",
    ano: 1996,
    gancho: "Un profesor de marketing montó una degustación de lujo para diez millonarios y ninguno tocó el foie. Uno le pidió una cerveza y le dijo que solo bebía dos marcas: la gratis y la barata.",
    porQue: "Porque separa dos cosas que casi todo el mundo confunde y que cuestan mucho dinero confundir: cobrar mucho y ser rico. Y porque su fórmula famosa no sale, y su método tiene el problema que Taleb lleva veinte años denunciando.",
    minutos: 25.6,
    capitulos: [
      { titulo: "Una degustación que nadie tocó", minutos: 5.2 },
      { titulo: "La camioneta del millonario", minutos: 5.1 },
      { titulo: "La fórmula que no sale", minutos: 5.1 },
      { titulo: "El cementerio que no se encuestó", minutos: 5.1 },
      { titulo: "Renta no es riqueza", minutos: 5.1 },
    ],
  },
  {
    id: "paseo-aleatorio",
    titulo: "Un paseo aleatorio por Wall Street",
    autor: "Burton Malkiel",
    ano: 1973,
    gancho: "Un mono con los ojos vendados tirando dardos a las páginas de bolsa elige una cartera tan buena como la de los expertos. Lleva cincuenta años sin que nadie lo desmienta del todo.",
    porQue: "Es el libro que explica por qué casi todo lo que se cobra por gestionar tu dinero no vale lo que cuesta, y lo demuestra con datos en vez de con indignación. Sirve igual para invertir que para desconfiar de cualquiera que prometa predecir el futuro.",
    minutos: 23.1,
    capitulos: [
      { titulo: "El mono con los ojos vendados", minutos: 4.5 },
      { titulo: "Tulipanes, mares del Sur y puntocom", minutos: 4.8 },
      { titulo: "Las dos maneras de fallar el pronóstico", minutos: 4.5 },
      { titulo: "Lo único que está en tu mano", minutos: 4.6 },
      { titulo: "Dónde cojea el paseo aleatorio", minutos: 4.7 },
    ],
  },
  {
    id: "repensar-pobreza",
    titulo: "Repensar la pobreza",
    autor: "Banerjee y Duflo",
    ano: 2011,
    gancho: "Una familia que no come suficiente se gasta el dinero en un televisor. El libro que se tomó en serio esa decisión ganó el Nobel de Economía.",
    porQue: "Es el libro que cambió la manera de repartir la ayuda al desarrollo, sustituyendo las grandes teorías por experimentos con grupo de control. Y su hallazgo central es que los pobres no se equivocan: deciden bien en condiciones que nosotros no tenemos.",
    minutos: 23.2,
    capitulos: [
      { titulo: "Un pueblo de Udaipur, Rajastán", minutos: 4.7 },
      { titulo: "La trampa del hambre", minutos: 4.7 },
      { titulo: "Los tres litros de cloro", minutos: 4.3 },
      { titulo: "La escuela sin maestro", minutos: 4.4 },
      { titulo: "Estocolmo, diciembre de 2019", minutos: 5 },
    ],
  },
  {
    id: "bogle-sentido-comun",
    titulo: "El pequeño libro para invertir con sentido común",
    autor: "John C. Bogle",
    ano: 2007,
    gancho: "Su fondo salió a bolsa en 1976 buscando ciento cincuenta millones y recaudó once. Lo llamaron la locura de Bogle. Cuarenta años después esa idea maneja billones y su inventor murió avisando de que se le había ido de las manos.",
    porQue: "Porque contiene el único argumento de inversión que se demuestra con una resta y no con una predicción. Y porque separar lo que Bogle demostró de lo que se le atribuye enseña a leer cualquier consejo financiero que te pongan delante.",
    minutos: 26.2,
    capitulos: [
      { titulo: "La locura de Bogle", minutos: 5.2 },
      { titulo: "La aritmética implacable", minutos: 5.3 },
      { titulo: "Los datos que le dieron la razón", minutos: 5.1 },
      { titulo: "Lo que el libro no cuenta", minutos: 5.3 },
      { titulo: "La advertencia que dejó escrita", minutos: 5.2 },
    ],
  },
  {
    id: "superpronosticadores",
    titulo: "Superpronosticadores",
    autor: "Philip E. Tetlock y Dan Gardner",
    ano: 2015,
    gancho: "Un psicólogo apuntó durante veinte años los pronósticos de 284 expertos y los corrigió como un examen. El experto medio acertaba menos que una regla tonta.",
    porQue: "Es el único libro que trata la predicción como algo medible en vez de como una opinión con traje. Y de ahí saca hábitos concretos que se pueden usar mañana: partir la pregunta, empezar por la frecuencia base y corregir poco a poco.",
    minutos: 24.4,
    capitulos: [
      { titulo: "Veinte años apuntando aciertos", minutos: 4.7 },
      { titulo: "El torneo que pagó el espionaje", minutos: 4.9 },
      { titulo: "Cómo piensan los que aciertan", minutos: 5.1 },
      { titulo: "Dónde deja de funcionar", minutos: 4.8 },
      { titulo: "Llevar la cuenta", minutos: 4.8 },
    ],
  },
  {
    id: "dinero-domina-juego",
    titulo: "Dinero: domina el juego",
    autor: "Tony Robbins",
    ano: 2014,
    gancho: "Un conferenciante motivacional sin ningún título financiero consiguió sentarse con cincuenta de los mayores inversores del mundo, entre ellos Buffett, Dalio y el fundador de Vanguard, y les preguntó lo que preguntaría cualquiera. Lo que le contestaron ocupa seiscientas páginas y no siempre le conviene.",
    porQue: "Porque su capítulo sobre comisiones es de lo mejor que se ha escrito para el público general, y porque el mismo libro que demuestra que las comisiones te arruinan te acaba mandando a una firma de asesoramiento en la que el autor tenía participación.",
    minutos: 27.2,
    capitulos: [
      { titulo: "Cincuenta entrevistas y una libreta", minutos: 5.2 },
      { titulo: "El uno por ciento que se lleva un tercio", minutos: 5.5 },
      { titulo: "La cartera de todas las estaciones", minutos: 5.5 },
      { titulo: "Quién cobra cuando sigues el consejo", minutos: 5.4 },
      { titulo: "Las tres frases que sobreviven", minutos: 5.5 },
    ],
  },
  {
    id: "nacidos-correr",
    titulo: "Nacidos para correr",
    autor: "Christopher McDougall",
    ano: 2009,
    gancho: "Fue al médico porque le dolía el pie corriendo. Acabó en un cañón de México con gente que corre cien kilómetros con sandalias de neumático.",
    porQue: "Cambió la manera de correr y de fabricar zapatillas de medio mundo a partir de una pregunta. Y después llegaron los ensayos clínicos y una demanda judicial.",
    minutos: 25.8,
    capitulos: [
      { titulo: "¿Por qué me duele el pie?", minutos: 5.2 },
      { titulo: "Los de los pies ligeros", minutos: 5.1 },
      { titulo: "El simio que suda", minutos: 5.2 },
      { titulo: "La carrera de 2006", minutos: 5.1 },
      { titulo: "La demanda de las zapatillas", minutos: 5.2 },
    ],
  },
  {
    id: "milagro-manana",
    titulo: "Mañanas milagrosas",
    autor: "Hal Elrod",
    ano: 2012,
    gancho: "Estuvo clínicamente muerto seis minutos a los veinte años. Doce años después escribió un método de una hora que han copiado dos millones de personas.",
    porQue: "Porque cuatro de sus seis prácticas están razonablemente respaldadas, y la afirmación central del libro sobre el sueño es sencillamente falsa.",
    minutos: 21.7,
    capitulos: [
      { titulo: "Seis minutos muerto", minutos: 4.4 },
      { titulo: "Las seis prácticas", minutos: 4.3 },
      { titulo: "No se negocia con el sueño", minutos: 4.6 },
      { titulo: "Los treinta primeros días", minutos: 4.1 },
      { titulo: "La hora que no importa", minutos: 4.2 },
    ],
  },
  {
    id: "invencible",
    titulo: "Invicto",
    autor: "Marcos Vázquez",
    ano: 2021,
    gancho: "El mismo principio que hace crecer un músculo —estrés controlado más descanso— aplicado a la cabeza. Con dos mil años de instrucciones ya escritas.",
    porQue: "Es la mejor traducción al español del estoicismo a un programa de entrenamiento, y también un buen sitio para ver dónde ese marco deja de funcionar.",
    minutos: 21,
    capitulos: [
      { titulo: "El esclavo cojo", minutos: 4.1 },
      { titulo: "Lo que depende de ti", minutos: 4.2 },
      { titulo: "Sobrecarga progresiva", minutos: 4.1 },
      { titulo: "El juez interior", minutos: 4.2 },
      { titulo: "Amor fati", minutos: 4.5 },
    ],
  },
  {
    id: "anticancer",
    titulo: "Anticáncer",
    autor: "David Servan-Schreiber",
    ano: 2007,
    gancho: "Un neurocientífico de treinta y un años se metió en su propio escáner para sustituir a un voluntario que no vino. Le encontraron un tumor cerebral.",
    porQue: "Es el libro sobre cáncer y estilo de vida más vendido de este siglo, escrito por un médico serio que además era el paciente. Merece leerse separando con cuidado lo que la evidencia sostiene de lo que él quería que fuera verdad.",
    minutos: 22.2,
    capitulos: [
      { titulo: "El escáner de Pittsburgh, 1992", minutos: 4.5 },
      { titulo: "La cocina", minutos: 4.5 },
      { titulo: "El gimnasio y la respiración", minutos: 4.2 },
      { titulo: "El informe del Fondo Mundial", minutos: 4.7 },
      { titulo: "El 24 de julio de 2011", minutos: 4.3 },
    ],
  },
  {
    id: "codigo-obesidad",
    titulo: "El código de la obesidad",
    autor: "Jason Fung",
    ano: 2016,
    gancho: "Un nefrólogo de Toronto llevaba años poniendo diálisis a diabéticos y un día se dio cuenta de que estaba tratando las complicaciones de una enfermedad que, según él, se podía revertir.",
    porQue: "Porque acierta en cosas que la nutrición oficial llevaba treinta años diciendo mal, y porque su mecanismo central se ha puesto a prueba en salas metabólicas después de 2016 y no ha salido bien parado.",
    minutos: 23.4,
    capitulos: [
      { titulo: "El nefrólogo que se hartó", minutos: 4.5 },
      { titulo: "Los treinta y seis hombres de Minnesota", minutos: 4.6 },
      { titulo: "La hormona que guarda", minutos: 4.5 },
      { titulo: "Cuándo comes", minutos: 4.4 },
      { titulo: "La sala metabólica de Kevin Hall", minutos: 5.4 },
    ],
  },
  {
    id: "dieta-cojea",
    titulo: "Mi dieta cojea",
    autor: "Aitor Sánchez García",
    ano: 2016,
    gancho: "En 2015, la pirámide alimentaria oficial española tenía cerveza y vino dentro, y estaba patrocinada, entre otros, por fabricantes de bollería y de bebidas alcohólicas.",
    porQue: "Porque es el libro que puso nombre en español a las mentiras que hay en cualquier supermercado, y porque su parte más útil —qué comer— es la más corta.",
    minutos: 23,
    capitulos: [
      { titulo: "El nutricionista que no estaba en el ambulatorio", minutos: 4.3 },
      { titulo: "La pirámide con cerveza dentro", minutos: 4.6 },
      { titulo: "El desayuno completo", minutos: 4.7 },
      { titulo: "Grupo uno no significa lo que crees", minutos: 4.6 },
      { titulo: "Vale, ¿y entonces qué como?", minutos: 4.8 },
    ],
  },
  {
    id: "milagro-metabolico",
    titulo: "El milagro metabólico",
    autor: "Carlos Jaramillo",
    ano: 2019,
    gancho: "Sostiene que el problema no son las calorías sino las hormonas. Acierta en la crítica al modelo viejo y se pasa de frenada al sustituirlo por una sola causa.",
    porQue: "Es el libro de salud más vendido en español de los últimos años y tiene una mitad sólida y otra que no se sostiene. Separarlas enseña a leer cualquier libro de nutrición, que es lo más útil que se puede sacar de este estante.",
    minutos: 23.4,
    capitulos: [
      { titulo: "Una consulta en Bogotá", minutos: 4.7 },
      { titulo: "Lo que sí está respaldado", minutos: 4.8 },
      { titulo: "La hipótesis de la insulina", minutos: 4.6 },
      { titulo: "El ayuno y el resto del botiquín", minutos: 4.8 },
      { titulo: "Cómo se lee un libro de salud", minutos: 4.5 },
    ],
  },
  {
    id: "vivir-plenitud",
    titulo: "Vivir con plenitud las crisis",
    autor: "Jon Kabat-Zinn",
    ano: 1990,
    gancho: "Un biólogo molecular montó en el sótano de un hospital una consulta para los pacientes que ya no mejoraban, y les enseñó a comerse una uva pasa.",
    porQue: "Es el manual del programa del que salió todo el mindfulness que hay hoy en hospitales, aplicaciones y oficinas. Merece la pena leer el original para ver qué prometía de verdad y qué le han colgado después.",
    minutos: 23.9,
    capitulos: [
      { titulo: "El sótano de Worcester", minutos: 4.9 },
      { titulo: "Una uva pasa", minutos: 5.1 },
      { titulo: "Cuarenta y cinco minutos tumbado", minutos: 4.7 },
      { titulo: "La consulta del dermatólogo", minutos: 4.6 },
      { titulo: "La sala de reuniones de Google", minutos: 4.7 },
    ],
  },
  {
    id: "poder-metabolismo",
    titulo: "El poder del metabolismo",
    autor: "Frank Suárez",
    ano: 2006,
    gancho: "El libro de salud más vendido en español lo escribió alguien sin ninguna titulación sanitaria, que vendía los suplementos que recomendaba. Y aun así acertó en la cosa que la medicina tardó otros diez años en admitir.",
    porQue: "Porque separar en este libro lo que funciona de lo que está inventado es el mejor ejercicio de lectura crítica que se puede hacer en salud. Y porque millones de personas en español lo usaron: merecen que alguien haga esa separación en serio, sin reírse de ellas.",
    minutos: 25.4,
    capitulos: [
      { titulo: "Un hombre de ciento treinta kilos con una libreta", minutos: 5 },
      { titulo: "Dos tipos de sistema nervioso que no existen", minutos: 5.2 },
      { titulo: "El plato partido en dos tercios", minutos: 5.3 },
      { titulo: "La tienda que hay detrás del libro", minutos: 4.9 },
      { titulo: "Lo que sí se le rompe a un cuerpo que ha hecho veinte dietas", minutos: 5.1 },
    ],
  },
];

/** Índice por identificador, que es como lo pide la pantalla. */
export const META_POR_ID: Record<string, FichaMeta> = Object.fromEntries(
  META.map((f) => [f.id, f]),
);
