/* ==========================================================================
   GENERADO por scripts/generar-meta.mjs — no editar a mano.

   Lo mínimo que hace falta para pintar la biblioteca sin descargar el texto
   de los libros: título, autor, año, las dos frases de la ficha y los minutos
   de cada capítulo, que son los que se ven parada por parada en el mapa del
   camino. El texto entero se pide aparte, al abrir un libro.

   Para regenerarlo:  npx tsx scripts/generar-meta.mjs
   ========================================================================== */

export type CapituloMeta = { titulo: string; minutos: number };

export type FichaMeta = {
  id: string;
  titulo: string;
  autor: string;
  ano: number;
  gancho: string;
  porQue: string;
  minutos: number;
  capitulos: CapituloMeta[];
};

export const META: FichaMeta[] = [
  {
    id: "sapiens",
    titulo: "Sapiens",
    autor: "Yuval Noah Harari",
    ano: 2011,
    gancho: "Nadie con antigüedad quería dar aquella asignatura de primero. Se la endosaron a un recién llegado.",
    porQue: "Cuenta la historia entera de nuestra especie en un solo hilo, y su tesis —que dominamos el planeta por creernos cosas que no existen— explica bastante más de lo que promete.",
    minutos: 25.4,
    capitulos: [
      { titulo: "Salida: la asignatura que nadie quería dar", minutos: 5.2 },
      { titulo: "Primera parada: creer en cosas que no existen", minutos: 5.1 },
      { titulo: "Segunda parada: el mayor fraude de la historia", minutos: 5 },
      { titulo: "Tercera parada: donde falla y qué no dice", minutos: 5 },
      { titulo: "Destino: la pregunta por la felicidad", minutos: 5 },
    ],
  },
  {
    id: "homo-deus",
    titulo: "Homo Deus",
    autor: "Yuval Noah Harari",
    ano: 2015,
    gancho: "Sapiens contaba de dónde venimos. Este empieza donde aquel acaba y pregunta qué haremos cuando ya no haya nada que resolver.",
    porQue: "Su primera parte es la mejor noticia que has leído nunca; la segunda es la más inquietante. Y las dos van juntas por necesidad.",
    minutos: 21.2,
    capitulos: [
      { titulo: "El hambre, la peste y la guerra", minutos: 4.6 },
      { titulo: "La muerte como problema técnico", minutos: 4.5 },
      { titulo: "El relato que nos gobierna", minutos: 4 },
      { titulo: "El algoritmo que te conoce mejor", minutos: 4.3 },
      { titulo: "Las preguntas que deja", minutos: 3.8 },
    ],
  },
  {
    id: "armas-germenes",
    titulo: "Armas, gérmenes y acero",
    autor: "Jared Diamond",
    ano: 1997,
    gancho: "Un político de Nueva Guinea le hizo una pregunta en una playa. Tardó veinticinco años en contestarla.",
    porQue: "Responde a la mayor pregunta de la historia —por qué unos pueblos conquistaron a otros— sin recurrir ni una vez a la inteligencia o la raza.",
    minutos: 25.6,
    capitulos: [
      { titulo: "Salida: una playa de Nueva Guinea, 1972", minutos: 5.2 },
      { titulo: "Primera parada: catorce animales de ciento cuarenta y ocho", minutos: 5.1 },
      { titulo: "Segunda parada: el eje que va de este a oeste", minutos: 5.1 },
      { titulo: "Tercera parada: Cajamarca, 16 de noviembre de 1532", minutos: 5.1 },
      { titulo: "Destino: lo que la geografía no explica", minutos: 5.2 },
    ],
  },
  {
    id: "diario-ana-frank",
    titulo: "Diario de Ana Frank",
    autor: "Ana Frank",
    ano: 1947,
    gancho: "Se lo regalaron por su cumpleaños, tres semanas antes de esconderse. Escribió en él veinticinco meses.",
    porQue: "Es el testimonio más leído del Holocausto porque no habla del Holocausto: habla de una adolescente discutiendo con su madre en un piso donde no se puede hacer ruido.",
    minutos: 25.9,
    capitulos: [
      { titulo: "Salida: un cuaderno de cuadros rojos", minutos: 5.2 },
      { titulo: "Primera parada: cincuenta metros cuadrados y ocho personas", minutos: 5.2 },
      { titulo: "Segunda parada: la radio de Londres que la volvió escritora", minutos: 5 },
      { titulo: "Tercera parada: lo que su padre quitó", minutos: 5.2 },
      { titulo: "Destino: la frase que todo el mundo cita mal", minutos: 5.3 },
    ],
  },
  {
    id: "pilares-tierra",
    titulo: "Los pilares de la Tierra",
    autor: "Ken Follett",
    ano: 1989,
    gancho: "Un autor de thrillers de éxito dejó de escribir espías para contar la construcción de una catedral. Su editor se opuso. Vendió veintisiete millones de ejemplares.",
    porQue: "Porque convierte una obra de albañilería del siglo XII en un thriller de mil páginas, y porque explica el arco apuntado mejor que cualquier manual.",
    minutos: 21.1,
    capitulos: [
      { titulo: "La horca de Shiring", minutos: 4.2 },
      { titulo: "Tom, el constructor", minutos: 4.3 },
      { titulo: "El prior Philip", minutos: 4.2 },
      { titulo: "El arco apuntado", minutos: 4.4 },
      { titulo: "Canterbury", minutos: 4 },
    ],
  },
  {
    id: "canones-agosto",
    titulo: "Los cañones de agosto",
    autor: "Barbara Tuchman",
    ano: 1962,
    gancho: "Un solo mes de 1914 contado en quinientas páginas. Kennedy lo leyó y lo repartió entre su gabinete justo antes de la crisis de los misiles de Cuba.",
    porQue: "Es el mejor libro que existe sobre cómo unos hombres razonables, con buenos planes, meten a un continente entero en una catástrofe en treinta días.",
    minutos: 21.3,
    capitulos: [
      { titulo: "Nueve reyes a caballo", minutos: 4.3 },
      { titulo: "El plan de un hombre muerto", minutos: 4.2 },
      { titulo: "Bélgica", minutos: 4.2 },
      { titulo: "El día más sangriento de Francia", minutos: 4.3 },
      { titulo: "El despacho de Kennedy", minutos: 4.4 },
    ],
  },
  {
    id: "historia-espana",
    titulo: "Una historia de España",
    autor: "Arturo Pérez-Reverte",
    ano: 2019,
    gancho: "Tres mil años de historia contados por un exreportero de guerra con muy mala leche, en columnas de página y media, sin una sola nota a pie.",
    porQue: "Porque es el libro de historia más vendido de España en la última década y no es un libro de historia. Saber exactamente qué es y qué no cambia por completo lo que uno se lleva de él.",
    minutos: 22.2,
    capitulos: [
      { titulo: "El columnista que se hartó", minutos: 4.5 },
      { titulo: "Numancia y el vicio de perder bien", minutos: 4.2 },
      { titulo: "El imperio que no sabía contar", minutos: 4.5 },
      { titulo: "Dos españas y un garrote", minutos: 4.4 },
      { titulo: "El espejo en el que nos gusta mirarnos", minutos: 4.5 },
    ],
  },
  {
    id: "tatuador",
    titulo: "El tatuador de Auschwitz",
    autor: "Heather Morris",
    ano: 2018,
    gancho: "Un hombre de ochenta y siete años que llevaba cincuenta callado, porque temía que si contaba lo que hizo en Auschwitz lo tomaran por colaborador.",
    porQue: "Porque ha vendido más de ocho millones de ejemplares y es, para mucha gente, su única idea de cómo era Auschwitz. Y porque el propio Museo de Auschwitz publicó un informe enumerando lo que tiene de falso.",
    minutos: 20.9,
    capitulos: [
      { titulo: "El número 32407", minutos: 4.3 },
      { titulo: "El hombre que marcaba brazos", minutos: 4.1 },
      { titulo: "34902", minutos: 4.1 },
      { titulo: "Los diamantes en el dobladillo", minutos: 4.1 },
      { titulo: "Melbourne, 2003", minutos: 4.4 },
    ],
  },
  {
    id: "guerra-civil-thomas",
    titulo: "La guerra civil española",
    autor: "Hugh Thomas",
    ano: 1961,
    gancho: "Un inglés de veintinueve años escribió la primera historia completa de la guerra de España. En España estuvo prohibida y entró de contrabando en maletas.",
    porQue: "Durante quince años fue el único libro donde un español podía leer lo que había pasado en su propio país. Hoy está superado en casi todo, y sigue siendo el mejor sitio para entender la guerra entera de una vez.",
    minutos: 23.4,
    capitulos: [
      { titulo: "Un funcionario que dimite por Suez", minutos: 4.9 },
      { titulo: "El 17 de julio de 1936", minutos: 4.7 },
      { titulo: "El Comité de No Intervención, Londres", minutos: 4.7 },
      { titulo: "El Ebro", minutos: 4.5 },
      { titulo: "Ruedo Ibérico, París, 1962", minutos: 4.6 },
    ],
  },
  {
    id: "auschwitz-rees",
    titulo: "Auschwitz: los nazis y la solución final",
    autor: "Laurence Rees",
    ano: 2005,
    gancho: "En mayo de 1940, el sitio era un cuartel abandonado en un pueblo polaco de doce mil habitantes y estaba pensado para presos políticos polacos. Nadie que estuviera allí aquel día había planeado lo que vendría después, y ese es exactamente el argumento del libro.",
    porQue: "Porque explica, paso a paso y con fechas, cómo se llegó hasta allí sin que exista una sola orden firmada; y porque corrige de raíz las dos cosas que casi todo el mundo cree: la cifra de la placa y la idea de que Auschwitz es donde murió la mayoría.",
    minutos: 26.9,
    capitulos: [
      { titulo: "Un cuartel de artillería en un pueblo polaco", minutos: 5.4 },
      { titulo: "Nadie encontró la orden firmada", minutos: 5.4 },
      { titulo: "La cifra de la placa", minutos: 5.3 },
      { titulo: "Los que intentaron pararlo", minutos: 5.3 },
      { titulo: "El contable que se sentó delante de la cámara", minutos: 5.5 },
    ],
  },
  {
    id: "postguerra",
    titulo: "Postguerra",
    autor: "Tony Judt",
    ano: 2005,
    gancho: "Europa en 1945 era un continente de escombros, hambre y treinta millones de muertos. Cómo salió de ahí es la mejor historia que se ha escrito de nuestro propio siglo.",
    porQue: "Explica de dónde salieron el estado del bienestar, la Unión Europea y la Transición española, y por qué nada de eso era inevitable. Y termina con la idea más incómoda del libro: que Europa se reconstruyó sobre un acuerdo de no recordar.",
    minutos: 24.3,
    capitulos: [
      { titulo: "El año cero", minutos: 5.1 },
      { titulo: "Los treinta años que parecieron normales", minutos: 5.6 },
      { titulo: "La mitad que se quedó al otro lado", minutos: 4.3 },
      { titulo: "1968, 1973 y la vuelta del sur", minutos: 4.6 },
      { titulo: "1989 y la deuda con los muertos", minutos: 4.8 },
    ],
  },
  {
    id: "homo-sovieticus",
    titulo: "El fin del Homo Sovieticus",
    autor: "Svetlana Aleksiévich",
    ano: 2013,
    gancho: "Veinte años grabando a gente corriente del imperio que se cayó. Le dieron el Nobel por ello, y también la llevaron a juicio por lo mismo: por lo que hace con las cintas cuando se sienta a escribir.",
    porQue: "Porque es el mejor retrato que existe de lo que le pasa por dentro a un país cuando se le acaba el mundo. Y porque su título original no dice lo que dice el español: no habla de un final, habla de ropa usada que alguien se ha vuelto a poner.",
    minutos: 25.9,
    capitulos: [
      { titulo: "Un mariscal se ahorca en su despacho del Kremlin", minutos: 5.1 },
      { titulo: "Cien horas de grabación para tres páginas", minutos: 5.2 },
      { titulo: "La libertad resultó ser el salchichón", minutos: 5.2 },
      { titulo: "El juicio de Minsk", minutos: 5.1 },
      { titulo: "Tiempo de segunda mano", minutos: 5.2 },
    ],
  },
  {
    id: "imperiofobia",
    titulo: "Imperiofobia y leyenda negra",
    autor: "María Elvira Roca Barea",
    ano: 2016,
    gancho: "Sostiene que España es el único imperio de la historia que se creyó la propaganda de sus enemigos. Vendió cientos de miles de ejemplares y los historiadores profesionales lo destrozaron.",
    porQue: "Porque lleva razón en muchos datos concretos que casi nadie conoce y usa el mismo método que denuncia. Leerlo bien enseña a la vez historia de España y algo más útil: cómo se fabrica el relato que un país se cuenta de sí mismo.",
    minutos: 24.6,
    capitulos: [
      { titulo: "Un panfleto impreso en Delft", minutos: 5 },
      { titulo: "Los datos que casi nadie conoce", minutos: 5.1 },
      { titulo: "Lo que le contestaron los historiadores", minutos: 4.8 },
      { titulo: "Cómo se fabrica el relato de un país", minutos: 4.9 },
      { titulo: "Qué hacer con un libro así", minutos: 4.8 },
    ],
  },
  {
    id: "brevedad-vida",
    titulo: "Sobre la brevedad de la vida",
    autor: "Séneca",
    ano: 49,
    gancho: "No tenemos poco tiempo: perdemos mucho. Lo escribió el hombre más rico de Roma mientras trabajaba para Nerón.",
    porQue: "Es la carta en la que un ministro le pide a su suegro que deje el cargo, y de paso el mejor texto antiguo sobre en qué se nos va la vida.",
    minutos: 25.8,
    capitulos: [
      { titulo: "La carta al hombre del trigo", minutos: 5.2 },
      { titulo: "El catálogo de los ocupados", minutos: 5.2 },
      { titulo: "Los tres tiempos y el pasado que no se mira", minutos: 5.1 },
      { titulo: "El millonario que predicaba el retiro", minutos: 5.2 },
      { titulo: "Un emperador, un esclavo y un ministro", minutos: 5.2 },
    ],
  },
  {
    id: "enquiridion",
    titulo: "Enquiridión",
    autor: "Epicteto",
    ano: 125,
    gancho: "Un manual de cincuenta y tres párrafos escrito por un esclavo liberto que nunca escribió nada, y que un piloto derribado sobre Vietnam recitaba de memoria en una celda.",
    porQue: "Porque es el libro de estoicismo más corto y más usado de los que existen, y porque su idea central —separar lo que depende de ti— es a la vez la más útil y la más tramposa del género.",
    minutos: 21.1,
    capitulos: [
      { titulo: "El alumno que tomaba notas", minutos: 4.1 },
      { titulo: "La primera frase", minutos: 4.1 },
      { titulo: "El jarrón roto", minutos: 4.3 },
      { titulo: "La obra la escribe otro", minutos: 4.2 },
      { titulo: "Hanói, 1965", minutos: 4.4 },
    ],
  },
  {
    id: "tao",
    titulo: "Tao Te Ching",
    autor: "Lao Tsé",
    ano: -400,
    gancho: "Cinco mil caracteres escritos, según la leyenda, en una tarde y a regañadientes, por un viejo que se marchaba del país y quería que le abrieran la puerta.",
    porQue: "Es uno de los libros más traducidos del mundo, contiene la idea política más rara que existe —gobernar sin intervenir— y casi nadie lo lee como lo que es.",
    minutos: 21.8,
    capitulos: [
      { titulo: "El paso de Hangu", minutos: 4.3 },
      { titulo: "Lo que no se puede nombrar", minutos: 4.4 },
      { titulo: "El vacío de la rueda", minutos: 4.2 },
      { titulo: "El agua", minutos: 4.5 },
      { titulo: "Cómo se cocina un pez pequeño", minutos: 4.3 },
    ],
  },
  {
    id: "etica-amador",
    titulo: "Ética para Amador",
    autor: "Fernando Savater",
    ano: 1991,
    gancho: "Un catedrático de filosofía le escribe a su hijo de quince años para explicarle por qué no piensa darle ni una sola norma de conducta.",
    porQue: "Es el libro de filosofía más leído en español del último medio siglo, y su tesis central sigue siendo la más incómoda: portarse bien es un asunto de egoísmo bien entendido.",
    minutos: 22,
    capitulos: [
      { titulo: "Una carta a un hijo de quince años", minutos: 4.4 },
      { titulo: "Las termitas no pueden elegir", minutos: 4.4 },
      { titulo: "Haz lo que quieras", minutos: 4.4 },
      { titulo: "Ponte en su lugar", minutos: 4.3 },
      { titulo: "Lo que respondió Amador", minutos: 4.5 },
    ],
  },
  {
    id: "etica-nicomaco",
    titulo: "Ética a Nicómaco",
    autor: "Aristóteles",
    ano: -340,
    gancho: "El primer manual de cómo vivir. No pregunta qué debes hacer, sino en quién te estás convirtiendo cada vez que lo haces.",
    porQue: "Es el origen de casi todo lo que hoy se dice sobre hábitos, carácter y amistad, y lo dice mejor que sus herederos. Leerlo entero enseña además a distinguir lo que sobrevive de un clásico de lo que caducó con su autor.",
    minutos: 25,
    capitulos: [
      { titulo: "Una escuela a las afueras de Atenas", minutos: 5.2 },
      { titulo: "El término medio no es la mitad", minutos: 5 },
      { titulo: "Se aprende tocando la cítara", minutos: 4.7 },
      { titulo: "Los amigos que hacen falta", minutos: 5.3 },
      { titulo: "La vida que se elige por sí misma", minutos: 4.8 },
    ],
  },
  {
    id: "apologia-socrates",
    titulo: "Apología de Sócrates",
    autor: "Platón",
    ano: -399,
    gancho: "Un hombre de setenta años tiene tres horas para salvar la vida ante quinientos jueces, y las gasta en irritarlos.",
    porQue: "Es el texto fundador de la filosofía occidental y se lee en una hora. También es el más malinterpretado: casi nada de lo que la gente cita de él está realmente escrito ahí.",
    minutos: 23.8,
    capitulos: [
      { titulo: "El pórtico del rey", minutos: 4.7 },
      { titulo: "El oráculo de Delfos", minutos: 4.5 },
      { titulo: "El interrogatorio de Meleto", minutos: 4.8 },
      { titulo: "La votación", minutos: 5 },
      { titulo: "La cicuta", minutos: 4.8 },
    ],
  },
  {
    id: "discurso-metodo",
    titulo: "Discurso del método",
    autor: "René Descartes",
    ano: 1637,
    gancho: "Un soldado de veintitrés años se queda encerrado por la nieve en una habitación con estufa, tiene tres sueños esa noche y decide refundar el conocimiento entero.",
    porQue: "Son sesenta páginas de las que sale la filosofía moderna y también la geometría analítica. Y la frase por la que se le conoce no está escrita como se cita, ni significa lo que se le hace decir.",
    minutos: 24.6,
    capitulos: [
      { titulo: "La habitación de la estufa, noviembre de 1619", minutos: 5.2 },
      { titulo: "El colegio de La Flèche", minutos: 4.8 },
      { titulo: "Las cuatro reglas", minutos: 4.7 },
      { titulo: "El cogito", minutos: 4.7 },
      { titulo: "Estocolmo, febrero de 1650", minutos: 5.1 },
    ],
  },
  {
    id: "contrato-social",
    titulo: "El contrato social",
    autor: "Jean-Jacques Rousseau",
    ano: 1762,
    gancho: "Lo quemaron en Ginebra y en París el mismo año de publicarse, y su autor tuvo que huir de tres países. Treinta años después, los revolucionarios franceses llevaron sus restos al Panteón en volandas.",
    porQue: "Porque de aquí sale la idea de que la ley solo obliga si la hemos hecho nosotros, que es el fundamento de cualquier democracia. Y porque casi todo lo que se le atribuye —el buen salvaje, la vuelta a la naturaleza, el gobierno de la mayoría— no está en el libro.",
    minutos: 26.1,
    capitulos: [
      { titulo: "Una frase que todo el mundo cita a medias", minutos: 5.1 },
      { titulo: "El buen salvaje que nunca escribió", minutos: 5.4 },
      { titulo: "La voluntad general no es la mayoría", minutos: 5.2 },
      { titulo: "El pueblo inglés cree ser libre", minutos: 5.2 },
      { titulo: "Los cinco niños del hospicio", minutos: 5.2 },
    ],
  },
  {
    id: "mas-alla-bien-mal",
    titulo: "Más allá del bien y del mal",
    autor: "Friedrich Nietzsche",
    ano: 1886,
    gancho: "Lo pagó de su bolsillo, se imprimieron seiscientos ejemplares y en el primer año vendió poco más de cien. Cuarenta años después, su hermana recibía a Hitler en el archivo donde guardaba sus papeles, con un libro suyo que él nunca escribió.",
    porQue: "Porque es el Nietzsche argumentado, el que explica en prosa lo que Zaratustra decía en parábolas. Y porque el título no significa lo que casi todo el mundo cree que significa: no es una licencia para hacer lo que a uno le dé la gana.",
    minutos: 27.5,
    capitulos: [
      { titulo: "Seiscientos ejemplares pagados de su bolsillo", minutos: 5.3 },
      { titulo: "El filósofo también tiene un cuerpo", minutos: 5.5 },
      { titulo: "Dos maneras de decir bueno", minutos: 5.7 },
      { titulo: "Lo que no se puede lavar", minutos: 5.4 },
      { titulo: "El archivo de Weimar", minutos: 5.6 },
    ],
  },
  {
    id: "existencialismo-humanismo",
    titulo: "El existencialismo es un humanismo",
    autor: "Jean-Paul Sartre",
    ano: 1946,
    gancho: "El texto filosófico más leído del siglo XX es la transcripción de una conferencia que su autor dio sin notas, en una sala donde la gente se desmayaba, y de cuya publicación se arrepintió el resto de su vida.",
    porQue: "Porque de aquí salen las tres frases que todo el mundo cita sobre la libertad. Y porque leerlo entero enseña algo que las frases sueltas ocultan: que no es una filosofía permisiva, sino la más exigente que hay en el estante.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Una sala rota en la rue Jean-Goujon", minutos: 5 },
      { titulo: "Un cortapapeles y un Dios que no está", minutos: 5.1 },
      { titulo: "El chico que no sabía si irse a Londres", minutos: 5.1 },
      { titulo: "La carta que le mandó Heidegger", minutos: 5.1 },
      { titulo: "Lo que Sartre dejó de creer", minutos: 5.2 },
    ],
  },
  {
    id: "segundo-sexo",
    titulo: "El segundo sexo",
    autor: "Simone de Beauvoir",
    ano: 1949,
    gancho: "Quiso escribir sobre sí misma y descubrió que lo primero que tenía que decir era: soy una mujer. Tardó dos años y mil páginas en explicar qué significaba eso.",
    porQue: "Es el libro del que sale casi todo el pensamiento feminista posterior, y la frase que más se cita de él se entiende mal casi siempre. Conviene saber qué dice de verdad, y también dónde se equivoca.",
    minutos: 23.4,
    capitulos: [
      { titulo: "Una terraza de Saint-Germain", minutos: 4.8 },
      { titulo: "La sala de lectura de la Nacional", minutos: 4.7 },
      { titulo: "No se nace mujer", minutos: 4.7 },
      { titulo: "La casada, la madre, la prostituta", minutos: 4.7 },
      { titulo: "El Índice de libros prohibidos", minutos: 4.4 },
    ],
  },
  {
    id: "ensayos-montaigne",
    titulo: "Ensayos",
    autor: "Michel de Montaigne",
    ano: 1580,
    gancho: "Se encerró en una torre a los treinta y ocho años para escribir sobre el único asunto que conocía de primera mano: él mismo. Inventó de paso un género entero.",
    porQue: "Es el primer libro moderno y sigue siendo el más honrado. Enseña un hábito que no caduca: preguntarle a cada cosa que uno cree si la creería igual habiendo nacido cuarenta leguas más allá.",
    minutos: 25,
    capitulos: [
      { titulo: "Una torre con frases en el techo", minutos: 5 },
      { titulo: "El hombre que se puso a sí mismo de tema", minutos: 5 },
      { titulo: "Contra la crueldad", minutos: 5 },
      { titulo: "La caída del caballo", minutos: 5 },
      { titulo: "Lo que hizo con los que vinieron después", minutos: 5.1 },
    ],
  },
  {
    id: "universo-cascara",
    titulo: "El universo en una cáscara de nuez",
    autor: "Stephen Hawking",
    ano: 2001,
    gancho: "Escribió la continuación de su libro más famoso porque le habían dicho que el primero no lo entendía nadie. El segundo tampoco es fácil, y explica cosas más raras.",
    porQue: "Porque su predicción más importante —que los agujeros negros se evaporan— sigue sin haberse observado, y eso explica por qué nunca le dieron el Nobel.",
    minutos: 21.8,
    capitulos: [
      { titulo: "Dos años de vida", minutos: 4.4 },
      { titulo: "La cáscara de nuez", minutos: 4.5 },
      { titulo: "Los agujeros negros no son negros", minutos: 4.4 },
      { titulo: "La apuesta de la enciclopedia", minutos: 4.4 },
      { titulo: "Lo que no se ha visto", minutos: 4.3 },
    ],
  },
  {
    id: "mundo-demonios",
    titulo: "El mundo y sus demonios",
    autor: "Carl Sagan",
    ano: 1995,
    gancho: "Un dragón invisible en un garaje explica, mejor que cualquier tratado, por qué algunas afirmaciones no significan nada.",
    porQue: "Es el manual de defensa contra camelos más leído que existe, escrito por alguien que sabía que se estaba muriendo mientras lo escribía.",
    minutos: 25.7,
    capitulos: [
      { titulo: "El taxista que preguntaba por la Atlántida", minutos: 5.1 },
      { titulo: "El dragón invisible del garaje", minutos: 5.1 },
      { titulo: "El kit de detección de camelos", minutos: 5.1 },
      { titulo: "Los demonios que antes eran brujas", minutos: 5.1 },
      { titulo: "La profecía que circula sin su libro", minutos: 5.2 },
    ],
  },
  {
    id: "astrofisica-prisa",
    titulo: "Astrofísica para gente con prisa",
    autor: "Neil deGrasse Tyson",
    ano: 2017,
    gancho: "Doscientas páginas para explicar de qué está hecho el universo. Y la respuesta incómoda es que el noventa y cinco por ciento no sabemos qué es.",
    porQue: "Es la puerta de entrada más rápida que existe a la cosmología moderna, y la única parte que no ha envejecido es la que más humildad exige.",
    minutos: 21.1,
    capitulos: [
      { titulo: "Los primeros tres minutos", minutos: 4.4 },
      { titulo: "El ruido de la televisión", minutos: 4.1 },
      { titulo: "Lo que no se ve", minutos: 4.1 },
      { titulo: "El universo que acelera", minutos: 4.3 },
      { titulo: "Somos polvo de estrellas", minutos: 4.3 },
    ],
  },
  {
    id: "vida-arboles",
    titulo: "La vida secreta de los árboles",
    autor: "Peter Wohlleben",
    ano: 2015,
    gancho: "Encontró un tocón sin hojas que llevaba siglos vivo. Los árboles de al lado lo estaban alimentando.",
    porQue: "Un guarda forestal con treinta años de bosque explica que los árboles se comunican, y lo hace sin una sola palabra técnica. Y en Alemania cuatro mil personas firmaron un manifiesto en contra.",
    minutos: 26.1,
    capitulos: [
      { titulo: "El tocón que llevaba siglos vivo", minutos: 5.2 },
      { titulo: "La red bajo el suelo", minutos: 5.4 },
      { titulo: "Cómo avisa una acacia", minutos: 5.2 },
      { titulo: "El bosque no es una comuna", minutos: 5.2 },
      { titulo: "Cuatro mil firmas contra un guarda forestal", minutos: 5.1 },
    ],
  },
  {
    id: "gen-historia",
    titulo: "El gen",
    autor: "Siddhartha Mukherjee",
    ano: 2016,
    gancho: "Un oncólogo viaja a Calcuta a visitar a su primo encerrado en un psiquiátrico. Va a escribir la historia de la herencia porque necesita saber qué lleva dentro.",
    porQue: "Cuenta ciento cincuenta años de genética como un thriller, y no esconde la parte en la que esta ciencia sirvió para esterilizar a sesenta mil personas.",
    minutos: 22.4,
    capitulos: [
      { titulo: "Un manicomio en Calcuta", minutos: 4.5 },
      { titulo: "El fraile y los guisantes", minutos: 4.6 },
      { titulo: "Tres generaciones de imbéciles", minutos: 4.4 },
      { titulo: "La fotografía 51", minutos: 4.4 },
      { titulo: "Lulu y Nana", minutos: 4.5 },
    ],
  },
  {
    id: "ultimos-dinosaurios",
    titulo: "Los últimos días de los dinosaurios",
    autor: "Riley Black",
    ano: 2022,
    gancho: "La primera hora después del impacto, contada minuto a minuto. El asteroide no mató a los dinosaurios: los mató lo que pasó en los meses siguientes.",
    porQue: "Reconstruye el peor día de la historia de la vida en la Tierra con el detalle de una crónica, y luego explica de dónde sale cada dato de esa crónica.",
    minutos: 21.7,
    capitulos: [
      { titulo: "La última tarde de Hell Creek", minutos: 4.3 },
      { titulo: "La hora del cielo en llamas", minutos: 4.4 },
      { titulo: "El invierno sin sol", minutos: 4.3 },
      { titulo: "Los que sobrevivieron en un agujero", minutos: 4.3 },
      { titulo: "Un millón de años después", minutos: 4.4 },
    ],
  },
  {
    id: "einstein",
    titulo: "Einstein: su vida y su universo",
    autor: "Walter Isaacson",
    ano: 2007,
    gancho: "Un funcionario de patentes de veintiséis años publica en un año cuatro artículos. Tres de ellos cambian la física. Y no, nunca suspendió matemáticas.",
    porQue: "Es la biografía que usó por primera vez sus cartas privadas, y el retrato que sale no es el del abuelo simpático de los pósters.",
    minutos: 21.7,
    capitulos: [
      { titulo: "La brújula", minutos: 4.4 },
      { titulo: "Montar sobre un rayo de luz", minutos: 4.5 },
      { titulo: "La oficina de patentes", minutos: 4.3 },
      { titulo: "El eclipse de 1919", minutos: 4.2 },
      { titulo: "Princeton", minutos: 4.4 },
    ],
  },
  {
    id: "feynman",
    titulo: "¿Está usted de broma, Sr. Feynman?",
    autor: "Richard Feynman",
    ano: 1985,
    gancho: "Un premio Nobel de física que se dedicaba a reventar las cajas fuertes con los secretos de la bomba atómica.",
    porQue: "Es el libro más divertido que existe sobre cómo piensa un científico, y no tiene una sola fórmula.",
    minutos: 25.6,
    capitulos: [
      { titulo: "Salida: una taza de té en Princeton", minutos: 5.1 },
      { titulo: "Primera parada: las cajas fuertes de Los Álamos", minutos: 5.1 },
      { titulo: "Segunda parada: un plato que se tambalea en una cafetería", minutos: 5.2 },
      { titulo: "Tercera parada: los capítulos que hoy incomodan", minutos: 5.1 },
      { titulo: "Destino: la ciencia de culto cargo", minutos: 5.2 },
    ],
  },
  {
    id: "musica-primos",
    titulo: "La música de los números primos",
    autor: "Marcus du Sautoy",
    ano: 2003,
    gancho: "En 1859 un alemán tímido escribió ocho páginas sobre los números primos. Ciento sesenta y seis años después, nadie ha conseguido demostrar la frase que dejó a medias.",
    porQue: "Porque es la mejor puerta de entrada al problema abierto más famoso de las matemáticas, y porque exagera en el único capítulo que todo el mundo cita: el de la criptografía.",
    minutos: 22.4,
    capitulos: [
      { titulo: "La conjetura de un chico de quince años", minutos: 4.5 },
      { titulo: "Las ocho páginas de Riemann", minutos: 4.6 },
      { titulo: "Todos los ceros en la misma recta", minutos: 4.4 },
      { titulo: "Los cazadores de ceros", minutos: 4.5 },
      { titulo: "El millón de dólares sigue en el banco", minutos: 4.5 },
    ],
  },
  {
    id: "universo-mano",
    titulo: "El universo en tu mano",
    autor: "Christophe Galfard",
    ano: 2015,
    gancho: "Un doctorando de Stephen Hawking se propuso contar toda la física del siglo veinte sin una sola ecuación, y llevándote a ti de excursión hasta el borde de lo que se sabe.",
    porQue: "Porque es el mejor viaje guiado por el universo que se ha escrito en este siglo, y porque en los tres últimos capítulos te lleva a sitios donde no hay ni una sola prueba experimental sin avisarte del todo.",
    minutos: 21.7,
    capitulos: [
      { titulo: "Tumbado en una playa", minutos: 4.1 },
      { titulo: "La fábrica de los átomos", minutos: 4.3 },
      { titulo: "El ruido que nadie conseguía quitar", minutos: 4.5 },
      { titulo: "Cuando nadie mira", minutos: 4.6 },
      { titulo: "El muro de Planck", minutos: 4.2 },
    ],
  },
  {
    id: "doble-helice",
    titulo: "La doble hélice",
    autor: "James D. Watson",
    ano: 1968,
    gancho: "Dos hombres que no hicieron ni un solo experimento resolvieron la estructura del ADN con los datos de una mujer que nadie consultó.",
    porQue: "Es el relato más honesto y más incómodo de cómo funciona la ciencia de verdad: con prisa, envidia y datos ajenos. Y es el documento que abrió el caso de Rosalind Franklin, aunque su autor no pretendiera abrirlo.",
    minutos: 23.3,
    capitulos: [
      { titulo: "Nápoles, primavera de 1951", minutos: 4.7 },
      { titulo: "El laboratorio Cavendish", minutos: 4.7 },
      { titulo: "Un modelo sin agua", minutos: 4.5 },
      { titulo: "La fotografía 51", minutos: 4.7 },
      { titulo: "Nature, 25 de abril de 1953", minutos: 4.7 },
    ],
  },
  {
    id: "revoluciones-cientificas",
    titulo: "La estructura de las revoluciones científicas",
    autor: "Thomas S. Kuhn",
    ano: 1962,
    gancho: "Un físico se sentó a leer a Aristóteles para dar una clase, le pareció un disparate, y de pronto entendió que el disparate era su manera de leerlo.",
    porQue: "De aquí sale la expresión «cambio de paradigma», que hoy se usa para vender móviles. Merece la pena saber qué significaba de verdad, porque el libro dice algo bastante más incómodo que lo que se le atribuye.",
    minutos: 23.2,
    capitulos: [
      { titulo: "Un despacho prestado en Harvard, 1947", minutos: 4.5 },
      { titulo: "La ciencia normal", minutos: 4.7 },
      { titulo: "La anomalía", minutos: 4.5 },
      { titulo: "La inconmensurabilidad", minutos: 4.7 },
      { titulo: "Un seminario en Londres, 1965", minutos: 4.8 },
    ],
  },
  {
    id: "siete-lecciones-fisica",
    titulo: "Siete breves lecciones de física",
    autor: "Carlo Rovelli",
    ano: 2014,
    gancho: "Noventa y seis páginas escritas para el suplemento dominical de un periódico económico. Vendieron más de un millón de ejemplares y convirtieron a un físico de Marsella en un autor de masas a los cincuenta y ocho años.",
    porQue: "Porque es el mejor libro que existe para entender qué siente un físico ante lo que estudia. Y porque hay que saber una cosa que el libro no dice con claridad: su quinta lección defiende la propia teoría del autor, que es minoritaria y no está confirmada.",
    minutos: 26.3,
    capitulos: [
      { titulo: "Siete artículos en el suplemento del domingo", minutos: 5.2 },
      { titulo: "La idea más bella de la ciencia", minutos: 5.2 },
      { titulo: "El mundo hecho de granos", minutos: 5.3 },
      { titulo: "El tiempo que no está en la ecuación", minutos: 5.3 },
      { titulo: "Nosotros, que estamos hechos de lo mismo", minutos: 5.2 },
    ],
  },
  {
    id: "orden-del-tiempo",
    titulo: "El orden del tiempo",
    autor: "Carlo Rovelli",
    ano: 2017,
    gancho: "En 2010, dos relojes atómicos colocados en la misma mesa, uno treinta y tres centímetros más alto que el otro, midieron ritmos distintos. No es una metáfora ni un experimento mental: es una medida de laboratorio con la altura de un escalón.",
    porQue: "Porque desmonta una a una las propiedades que damos por seguras del tiempo y luego reconstruye por qué lo sentimos como lo sentimos. Y porque su tercera parte no es física establecida, sino la teoría del propio autor, y eso el libro no lo señala tan claro como debería.",
    minutos: 26.8,
    capitulos: [
      { titulo: "Dos relojes separados por treinta y tres centímetros", minutos: 5.4 },
      { titulo: "El presente extendido de Próxima Centauri", minutos: 5.4 },
      { titulo: "La ecuación en la que no aparece el tiempo", minutos: 5.3 },
      { titulo: "El borrón que somos nosotros", minutos: 5.3 },
      { titulo: "La hermana del sueño", minutos: 5.5 },
    ],
  },
  {
    id: "henrietta-lacks",
    titulo: "La vida inmortal de Henrietta Lacks",
    autor: "Rebecca Skloot",
    ano: 2010,
    gancho: "Le quitaron dos trozos de tejido sin decírselo. Ocho meses después había muerto, y sus células no han dejado de crecer desde entonces.",
    porQue: "Es la historia de la primera línea celular humana inmortal contada desde la familia que no supo nada durante veintidós años. Se estudia en las facultades de medicina porque convirtió un reactivo de laboratorio en una persona con nombre.",
    minutos: 23.3,
    capitulos: [
      { titulo: "Un bulto en el útero", minutos: 4.7 },
      { titulo: "El sótano de George Gey", minutos: 4.5 },
      { titulo: "Bedford Springs, 1966", minutos: 4.7 },
      { titulo: "Crownsville", minutos: 4.7 },
      { titulo: "La lápida de Clover", minutos: 4.6 },
    ],
  },
  {
    id: "emperador-males",
    titulo: "El emperador de todos los males",
    autor: "Siddhartha Mukherjee",
    ano: 2010,
    gancho: "La biografía de una enfermedad de cuatro mil años, escrita por un oncólogo que la trataba mientras la escribía. Ganó el Pulitzer y no consuela a nadie.",
    porQue: "Cuenta cómo se aprende medicina de verdad: probando cosas atroces, equivocándose durante décadas enteras y descubriendo tarde que el error estaba en la pregunta. Es la mejor historia disponible de por qué la ciencia avanza tan despacio y tan a trompicones.",
    minutos: 23.6,
    capitulos: [
      { titulo: "El sótano del hospital de niños", minutos: 4.7 },
      { titulo: "El cirujano que cortaba cada vez más", minutos: 4.6 },
      { titulo: "La guerra que se declaró demasiado pronto", minutos: 4.5 },
      { titulo: "El humo que nadie quería ver", minutos: 4.6 },
      { titulo: "Un gen propio que se ha vuelto loco", minutos: 5.2 },
    ],
  },
  {
    id: "pulgar-panda",
    titulo: "El pulgar del panda",
    autor: "Stephen Jay Gould",
    ano: 1980,
    gancho: "La mejor prueba de la evolución no son los animales perfectos: son las chapuzas. Un hueso de la muñeca convertido en dedo para pelar bambú.",
    porQue: "Es la respuesta más elegante que existe a quien dice que el ojo es demasiado complejo para haber evolucionado. Y enseña a discutir: el autor pasó la vida peleándose con otro biólogo de esta misma biblioteca, y los dos tenían parte de razón.",
    minutos: 25.2,
    capitulos: [
      { titulo: "Un sexto dedo que no es un dedo", minutos: 5.2 },
      { titulo: "Las rocas que decían la verdad", minutos: 5 },
      { titulo: "Las enjutas de San Marcos", minutos: 4.9 },
      { titulo: "El que mide también tiene sesgos", minutos: 5.2 },
      { titulo: "La pelea con el gen egoísta", minutos: 5 },
    ],
  },
  {
    id: "cuchara-menguante",
    titulo: "La cuchara menguante",
    autor: "Sam Kean",
    ano: 2010,
    gancho: "Una broma de laboratorio: dar el té a una visita con una cucharilla que se derrite al removerlo. El metal existe, se llama galio, y da título al libro que convirtió la tabla periódica en un anecdotario.",
    porQue: "Porque hay diez historias aquí que se recuerdan para siempre y ninguna se aprende en el colegio. Y porque conviene saber qué clase de libro es: no explica cómo funciona la tabla periódica, y su anécdota más famosa está contada en la versión bonita y no en la verdadera.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Una cuchara que se derrite en el té", minutos: 5.1 },
      { titulo: "El hombre que corrigió una medición sin ver el metal", minutos: 5.1 },
      { titulo: "El oro que sirvió para tapar baches", minutos: 5 },
      { titulo: "Las chicas que se pintaban los dientes", minutos: 5.1 },
      { titulo: "El hueco número cuarenta y tres", minutos: 5.2 },
    ],
  },
  {
    id: "sexta-extincion",
    titulo: "La sexta extinción",
    autor: "Elizabeth Kolbert",
    ano: 2014,
    gancho: "Ha habido cinco extinciones masivas en quinientos millones de años. La sexta la está causando un animal que sabe lo que está haciendo y lo escribe en libros.",
    porQue: "Es el mejor libro para entender la crisis ecológica sin consignas: va al sitio, se pone al lado del científico y cuenta lo que se mide. Y de paso enseña algo más raro, que es cómo una idea imposible —que una especie pueda desaparecer— se convirtió en un hecho.",
    minutos: 23.1,
    capitulos: [
      { titulo: "Una rana dorada en un hotel de Panamá", minutos: 4.2 },
      { titulo: "El hombre que inventó la extinción", minutos: 4.4 },
      { titulo: "Las cinco veces que casi se acaba todo", minutos: 6.1 },
      { titulo: "El mar que se está agriando", minutos: 4.3 },
      { titulo: "El animal que mueve las cosas de sitio", minutos: 4.2 },
    ],
  },
  {
    id: "roba-artista",
    titulo: "Roba como un artista",
    autor: "Austin Kleon",
    ano: 2012,
    gancho: "Un poeta que tachaba periódicos con rotulador convirtió una charla improvisada en el manual de creatividad más regalado de la década.",
    porQue: "Es el libro que más gente cita para justificar que copia, y dice casi lo contrario de lo que se le atribuye.",
    minutos: 25.6,
    capitulos: [
      { titulo: "El poeta que tachaba periódicos", minutos: 5.1 },
      { titulo: "La charla de abril de 2011", minutos: 5.1 },
      { titulo: "Las diez cosas de la lista", minutos: 5.1 },
      { titulo: "Sé aburrido, dice el libro", minutos: 5.2 },
      { titulo: "Robar bien, y hasta dónde llega", minutos: 5.1 },
    ],
  },
  {
    id: "camino-artista",
    titulo: "El camino del artista",
    autor: "Julia Cameron",
    ano: 1992,
    gancho: "Dejó de beber a los treinta años convencida de que el alcohol era lo que la hacía escribir. Descubrió que era al revés y montó un curso de doce semanas.",
    porQue: "Es el libro que ha desbloqueado a más gente creativa que ningún otro, y su herramienta principal cabe en tres folios y un bolígrafo.",
    minutos: 21.3,
    capitulos: [
      { titulo: "El día que dejó de beber", minutos: 4.3 },
      { titulo: "Tres páginas a mano", minutos: 4.4 },
      { titulo: "La cita con el artista", minutos: 4.3 },
      { titulo: "Los artistas en la sombra", minutos: 4.1 },
      { titulo: "Salta y aparecerá la red", minutos: 4.2 },
    ],
  },
  {
    id: "leonardo",
    titulo: "Leonardo da Vinci",
    autor: "Walter Isaacson",
    ano: 2017,
    gancho: "Entre sus notas hay una tarea pendiente: describir la lengua del pájaro carpintero. Nadie se lo había encargado y nunca cobró por ello.",
    porQue: "Reconstruye al personaje a partir de siete mil doscientas páginas de cuadernos. Su tesis es que el genio era curiosidad entrenada, y ahí es donde el libro convence y donde se pasa de frenada.",
    minutos: 26,
    capitulos: [
      { titulo: "Hijo de notario, sin latín", minutos: 5.4 },
      { titulo: "Describir la lengua del pájaro carpintero", minutos: 5.3 },
      { titulo: "La carta a Ludovico Sforza", minutos: 5.2 },
      { titulo: "Treinta cadáveres y una sonrisa", minutos: 5.1 },
      { titulo: "Los cuadernos que nadie leyó", minutos: 5.1 },
    ],
  },
  {
    id: "arte-sin-hombres",
    titulo: "Historia del arte sin hombres",
    autor: "Katy Hessel",
    ano: 2022,
    gancho: "En una feria de arte de Londres con miles de obras no había ni una sola de una mujer. La que se dio cuenta tenía veintiún años y decidió escribir el otro libro.",
    porQue: "Es la respuesta directa al manual de Gombrich, y no va de opinar: va de enseñar los mecanismos concretos por los que media historia del arte desapareció.",
    minutos: 22,
    capitulos: [
      { titulo: "Una feria sin una sola mujer", minutos: 4.4 },
      { titulo: "El juicio de Artemisia", minutos: 4.4 },
      { titulo: "Las dos que solo están en el cuadro", minutos: 4.3 },
      { titulo: "La abstracción llegó antes", minutos: 4.6 },
      { titulo: "¿Hay que estar desnuda?", minutos: 4.3 },
    ],
  },
  {
    id: "vida-dali",
    titulo: "La vida secreta de Salvador Dalí",
    autor: "Salvador Dalí",
    ano: 1942,
    gancho: "Sus padres le pusieron el nombre de un hermano muerto nueve meses antes de nacer él. A los cinco años lo llevaron a su tumba y le dijeron que era su reencarnación.",
    porQue: "Es la autobiografía más mentirosa que se ha escrito y sigue siendo imprescindible, porque la mentira es exactamente el objeto de estudio.",
    minutos: 21.6,
    capitulos: [
      { titulo: "La tumba del hermano", minutos: 4.5 },
      { titulo: "La Residencia", minutos: 4.2 },
      { titulo: "Gala", minutos: 4.4 },
      { titulo: "Ávida Dollars", minutos: 4.4 },
      { titulo: "La cripta de Figueres", minutos: 4.2 },
    ],
  },
  {
    id: "diarios-frida",
    titulo: "El diario de Frida Kahlo",
    autor: "Frida Kahlo",
    ano: 1995,
    gancho: "Ciento setenta páginas que nunca quiso que se publicaran. Se editaron en facsímil cuarenta y un años después de su muerte, con las manchas incluidas.",
    porQue: "Porque es el documento más íntimo del arte del siglo XX, y porque leerlo obliga a preguntarse qué derecho tiene nadie a leer el cuaderno privado de una muerta.",
    minutos: 21.6,
    capitulos: [
      { titulo: "El pasamanos", minutos: 4.4 },
      { titulo: "El espejo del dosel", minutos: 4.3 },
      { titulo: "Diego", minutos: 4.4 },
      { titulo: "Pies para qué los quiero", minutos: 4.3 },
      { titulo: "La cama en la galería", minutos: 4.1 },
    ],
  },
  {
    id: "van-gogh-cartas",
    titulo: "Cartas a Theo",
    autor: "Vincent van Gogh",
    ano: 1914,
    gancho: "Pintó unas dos mil obras en diez años y solo se le documenta una venta. Su hermano le pagó cada tubo de pintura.",
    porQue: "Las cartas desmontan el mito del loco que pintaba por instinto: era un lector voraz que razonaba cada color. Y existen porque una viuda de veintiocho años decidió que existieran.",
    minutos: 26.6,
    capitulos: [
      { titulo: "El evangelista despedido de las minas", minutos: 5.2 },
      { titulo: "Ciento cincuenta francos al mes", minutos: 5.5 },
      { titulo: "Por qué este rojo va contra este verde", minutos: 5.2 },
      { titulo: "La oreja de la que no habla", minutos: 5.3 },
      { titulo: "La viuda que inventó a Van Gogh", minutos: 5.3 },
    ],
  },
  {
    id: "sobre-fotografia",
    titulo: "Sobre la fotografía",
    autor: "Susan Sontag",
    ano: 1977,
    gancho: "Es el libro más influyente que se ha escrito sobre fotografía y no contiene ni una sola fotografía. La decisión es deliberada y es también su mayor defecto.",
    porQue: "Porque describió en 1977 un mundo saturado de imágenes que entonces no existía y hoy es el nuestro, y porque su autora corrigió públicamente la tesis central veintiséis años después.",
    minutos: 22.8,
    capitulos: [
      { titulo: "Una librería de Santa Mónica, julio de 1945", minutos: 4.5 },
      { titulo: "En la caverna de Platón", minutos: 4.7 },
      { titulo: "Disparar", minutos: 4.4 },
      { titulo: "La anestesia", minutos: 4.4 },
      { titulo: "Ante el dolor de los demás", minutos: 4.8 },
    ],
  },
  {
    id: "magia-crear",
    titulo: "La magia de crear",
    autor: "Elizabeth Gilbert",
    ano: 2015,
    gancho: "Sostiene que las ideas son criaturas conscientes que van buscando un colaborador humano, y que si tú no la coges se marcha a otra casa. Y cuenta el caso concreto en el que dice que le pasó, con nombre y apellido de la escritora que la recibió.",
    porQue: "Porque su consejo central va contra todo lo que dice el género: no dejes el trabajo, no le pidas a tu arte que te pague el alquiler. Y porque la autora acabó haciendo con un libro suyo exactamente lo contrario de lo que este libro predica.",
    minutos: 27.5,
    capitulos: [
      { titulo: "Una novela que se fue a otra casa", minutos: 6 },
      { titulo: "Tener un genio en vez de serlo", minutos: 5.3 },
      { titulo: "No le pidas a tu arte que te pague el alquiler", minutos: 5.5 },
      { titulo: "El problema de escribirlo desde arriba", minutos: 5.3 },
      { titulo: "El libro que retiró", minutos: 5.4 },
    ],
  },
  {
    id: "pajaro-a-pajaro",
    titulo: "Pájaro a pájaro",
    autor: "Anne Lamott",
    ano: 1994,
    gancho: "Un niño de diez años lleva tres meses con un trabajo sobre pájaros y lo tiene que entregar mañana. Está paralizado. Su padre se sienta a su lado.",
    porQue: "No enseña a escribir bien: enseña a escribir mal a propósito, que es el requisito previo que nadie cuenta. Y dice en voz alta lo que ningún libro del género dice: que publicar no arregla nada.",
    minutos: 22.7,
    capitulos: [
      { titulo: "La mesa del comedor, en Marin County", minutos: 4.4 },
      { titulo: "El primer borrador de mierda", minutos: 4.5 },
      { titulo: "La emisora que suena dentro", minutos: 4.6 },
      { titulo: "El marco de un palmo", minutos: 4.7 },
      { titulo: "El día que sale el libro", minutos: 4.5 },
    ],
  },
  {
    id: "vidas-vasari",
    titulo: "Las vidas de los más excelentes pintores, escultores y arquitectos",
    autor: "Giorgio Vasari",
    ano: 1550,
    gancho: "Casi todo lo que crees saber sobre los artistas del Renacimiento lo escribió un pintor de Arezzo que conocía a la mitad de ellos.",
    porQue: "Es el primer libro de historia del arte que se escribió, y sigue siendo la fuente de casi todas las anécdotas que circulan sobre Giotto, Leonardo o Miguel Ángel. También es donde nacieron algunos de los errores que todavía repetimos.",
    minutos: 23.8,
    capitulos: [
      { titulo: "Una cena en casa del cardenal", minutos: 4.8 },
      { titulo: "El niño que dibujaba ovejas", minutos: 4.8 },
      { titulo: "Las puertas del Paraíso", minutos: 4.7 },
      { titulo: "El funeral de San Lorenzo", minutos: 4.8 },
      { titulo: "El muro de la Sala de los Quinientos", minutos: 4.7 },
    ],
  },
  {
    id: "espiritual-arte",
    titulo: "De lo espiritual en el arte",
    autor: "Vasili Kandinsky",
    ano: 1911,
    gancho: "El libro con el que un pintor se dio permiso para dejar de pintar cosas. Su teoría del color es casi toda falsa y aun así cambió lo que se cuelga en las paredes.",
    porQue: "Porque explica de dónde salió el arte abstracto, que es lo que más incomoda al visitante de un museo. Y enseña una manera concreta de mirar un cuadro que no representa nada, que es dejar de preguntar qué es.",
    minutos: 24,
    capitulos: [
      { titulo: "Un cuadro apoyado del revés", minutos: 4.9 },
      { titulo: "El amarillo suena a trompeta", minutos: 4.9 },
      { titulo: "La necesidad interior", minutos: 4.8 },
      { titulo: "La mujer que llegó cuatro años antes", minutos: 4.8 },
      { titulo: "Del Bauhaus a la pared del salón", minutos: 4.7 },
    ],
  },
  {
    id: "reproductibilidad",
    titulo: "La obra de arte en la época de su reproductibilidad técnica",
    autor: "Walter Benjamin",
    ano: 1936,
    gancho: "Un refugiado alemán sin trabajo escribió en un café de París por qué una foto de un cuadro no es el cuadro. Cuatro años después murió en la frontera española.",
    porQue: "Es el ensayo del que salió todo lo que se dice hoy sobre imágenes, copias y originales. Y casi nadie lo lee: se citan cuatro frases suyas, casi siempre al revés de lo que él quería decir.",
    minutos: 22.5,
    capitulos: [
      { titulo: "El Instituto en el exilio", minutos: 4.5 },
      { titulo: "El aura", minutos: 4.8 },
      { titulo: "La sala de montaje", minutos: 4.6 },
      { titulo: "El estadio de Núremberg", minutos: 4.2 },
      { titulo: "Portbou, 26 de septiembre de 1940", minutos: 4.3 },
    ],
  },
  {
    id: "heroe-mil-caras",
    titulo: "El héroe de las mil caras",
    autor: "Joseph Campbell",
    ano: 1949,
    gancho: "Un hombre sin doctorado, que se pasó cinco años sin trabajo leyendo nueve horas al día en una cabaña, escribió el esquema con el que se construyen hoy la mitad de las películas de Hollywood.",
    porQue: "Porque su estructura funciona sorprendentemente bien para escribir historias y es bastante mala como descripción de la mitología del mundo, y casi nadie distingue las dos cosas.",
    minutos: 22,
    capitulos: [
      { titulo: "Cinco años leyendo en una cabaña", minutos: 4.5 },
      { titulo: "El monomito", minutos: 4.2 },
      { titulo: "El rancho Skywalker, 1983", minutos: 4.5 },
      { titulo: "Los mitos que no encajan", minutos: 4.6 },
      { titulo: "La diosa y la tentadora", minutos: 4.1 },
    ],
  },
  {
    id: "el-elemento",
    titulo: "El elemento",
    autor: "Ken Robinson",
    ano: 2009,
    gancho: "La charla más vista de la historia de TED se apoya en una estadística que la NASA nunca hizo. Y el argumento, curiosamente, aguanta igual sin ella.",
    porQue: "Porque es el libro que convenció a media docena de generaciones de que el colegio les había escondido algo. Vale la pena separar lo que Robinson demostró de lo que solo contó bien, porque las dos cosas están mezcladas y la segunda es la que más se repite.",
    minutos: 25,
    capitulos: [
      { titulo: "Una niña que no paraba quieta", minutos: 5 },
      { titulo: "Diecinueve minutos en Monterrey", minutos: 5 },
      { titulo: "El test que la NASA nunca hizo", minutos: 5.1 },
      { titulo: "La escuela que dicen que es una fábrica", minutos: 4.9 },
      { titulo: "Lo que aguanta cuando le quitas las cifras", minutos: 5 },
    ],
  },
  {
    id: "mujercitas",
    titulo: "Mujercitas",
    autor: "Louisa May Alcott",
    ano: 1868,
    gancho: "Le encargaron un libro para chicas. Escribió en su diario que no le apetecía nada, que nunca le habían gustado las chicas y que no conocía a ninguna aparte de sus hermanas. Lo terminó en diez semanas.",
    porQue: "Porque el libro que enseñó a varias generaciones de mujeres que se podía querer otra cosa lo escribió alguien que estaba negociando, capítulo a capítulo, con lo que su editor le dejaba escribir.",
    minutos: 22.1,
    capitulos: [
      { titulo: "Fruitlands, siete meses", minutos: 4.5 },
      { titulo: "Un libro para chicas", minutos: 4.2 },
      { titulo: "No voy a casar a Jo con Laurie", minutos: 4.4 },
      { titulo: "La casa de Concord", minutos: 4.6 },
      { titulo: "El escritorio entre dos ventanas", minutos: 4.4 },
    ],
  },
  {
    id: "cuentos-poe",
    titulo: "Cuentos de Edgar Allan Poe",
    autor: "Edgar Allan Poe",
    ano: 1845,
    gancho: "Inventó el relato de detectives, fijó las reglas del cuento moderno y escribió el poema más famoso de su país. Cobró nueve dólares por él y murió nueve años después, delirando, con la ropa de otro hombre.",
    porQue: "Porque casi todo lo que la gente cree saber de él lo escribió el hombre que lo odiaba, y porque su fama de autor de terror esconde que inventó dos géneros enteros.",
    minutos: 22,
    capitulos: [
      { titulo: "Un huérfano en Richmond", minutos: 4.1 },
      { titulo: "El hombre del tomahawk", minutos: 4.5 },
      { titulo: "El corazón debajo del suelo", minutos: 4.5 },
      { titulo: "El cuervo y los nueve dólares", minutos: 4.4 },
      { titulo: "Baltimore, 3 de octubre de 1849", minutos: 4.5 },
    ],
  },
  {
    id: "elegancia-erizo",
    titulo: "La elegancia del erizo",
    autor: "Muriel Barbery",
    ano: 2006,
    gancho: "Una portera de cincuenta y cuatro años finge ser tonta durante veintisiete años para que la dejen en paz, mientras lee a Tolstói y a Husserl en el cuarto de atrás.",
    porQue: "Porque vendió millones de ejemplares por el boca a boca y porque su idea de fondo —que la cultura es la verdadera aristocracia— es a la vez lo que lo hace emocionante y lo que lo hace tramposo.",
    minutos: 21.8,
    capitulos: [
      { titulo: "La portera del número 7", minutos: 4.2 },
      { titulo: "Una niña con fecha", minutos: 4.4 },
      { titulo: "Todas las familias felices se parecen", minutos: 4.6 },
      { titulo: "La furgoneta de la tintorería", minutos: 4.3 },
      { titulo: "Camelias sobre el musgo", minutos: 4.4 },
    ],
  },
  {
    id: "el-tunel",
    titulo: "El túnel",
    autor: "Ernesto Sabato",
    ano: 1948,
    gancho: "Lo escribió un doctor en física que había trabajado en el laboratorio Curie y que a los treinta y cuatro años abandonó la ciencia para siempre. Es la mejor novela en español sobre un razonamiento impecable que termina en un crimen.",
    porQue: "Porque en ciento cincuenta páginas enseña algo que no se aprende de otra manera: cómo se construye una certeza absoluta a partir de nada, paso a paso, sin que ninguno de los pasos sea ilógico. Y porque casi todo el mundo la lee olvidando quién la está contando.",
    minutos: 26.2,
    capitulos: [
      { titulo: "El primer párrafo dice quién y a quién", minutos: 5.3 },
      { titulo: "Una ventanita en la esquina de un cuadro", minutos: 5.2 },
      { titulo: "La cadena de razonamientos", minutos: 5.2 },
      { titulo: "Todo lo que sabemos de María", minutos: 5.3 },
      { titulo: "Dos túneles paralelos", minutos: 5.2 },
    ],
  },
  {
    id: "renglones-torcidos",
    titulo: "Los renglones torcidos de Dios",
    autor: "Torcuato Luca de Tena",
    ano: 1979,
    gancho: "Para escribirla, el director de un periódico nacional se hizo ingresar en un psiquiátrico durante dieciocho días. Solo el director del centro sabía que no estaba enfermo, y ni siquiera él sabía cómo iba a salir de allí.",
    porQue: "Porque plantea la pregunta más incómoda que existe: cómo demostrarías que estás cuerdo si nadie te creyera. Y porque el experimento científico que hizo esa misma pregunta seis años antes acabó, cuarenta años después, resultando bastante menos limpio de lo que decía.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Dieciocho días de ingreso voluntario", minutos: 5.3 },
      { titulo: "Una detective que dice ser detective", minutos: 5 },
      { titulo: "El experimento que se le adelantó seis años", minutos: 4.9 },
      { titulo: "Los internos", minutos: 5.2 },
      { titulo: "Renglones torcidos", minutos: 5.2 },
    ],
  },
  {
    id: "nudge",
    titulo: "Un pequeño empujón",
    autor: "Thaler y Sunstein",
    ano: 2008,
    gancho: "Retiró el cuenco de anacardos antes de cenar y sus invitados le dieron las gracias. Un economista no debería alegrarse de tener menos opciones.",
    porQue: "Cambió cómo diseñan políticas media docena de gobiernos, le dio un Nobel a su autor, y quince años después la mitad de sus pruebas están en discusión.",
    minutos: 21.2,
    capitulos: [
      { titulo: "El cuenco de anacardos", minutos: 4.3 },
      { titulo: "La mosca del urinario", minutos: 4.3 },
      { titulo: "Ahorra más mañana", minutos: 4.2 },
      { titulo: "La unidad de empujones", minutos: 4.3 },
      { titulo: "La crisis de replicación", minutos: 4.2 },
    ],
  },
  {
    id: "educada",
    titulo: "Una educación",
    autor: "Tara Westover",
    ano: 2018,
    gancho: "Pisó un aula por primera vez a los diecisiete años. Diez años después era doctora por Cambridge.",
    porQue: "Plantea la pregunta más difícil, qué haces cuando educarte te separa de tu familia, y es honesto sobre lo poco fiable que es su propia memoria.",
    minutos: 26.1,
    capitulos: [
      { titulo: "La montaña sin partida de nacimiento", minutos: 5.2 },
      { titulo: "El chatarrero y la comadrona", minutos: 5.1 },
      { titulo: "El examen que se estudió sola", minutos: 5.3 },
      { titulo: "La palabra que no conocía", minutos: 5.3 },
      { titulo: "Lo que costó la educación", minutos: 5.2 },
    ],
  },
  {
    id: "cerebro-del-nino",
    titulo: "El cerebro del niño",
    autor: "Siegel y Payne Bryson",
    ano: 2011,
    gancho: "Doce estrategias para criar, todas envueltas en neurociencia. Los consejos son buenos y llevan décadas funcionando. La neurociencia, en cambio, está ahí sobre todo para que te los creas.",
    porQue: "Porque es el manual de crianza más vendido de los últimos quince años y merece que alguien separe lo que está probado de lo que está decorado. Y porque hay un experimento de 1975, que el libro apenas menciona, que demuestra su tesis mejor que todas sus resonancias juntas.",
    minutos: 26.2,
    capitulos: [
      { titulo: "Una rabieta en el asiento de atrás", minutos: 5.4 },
      { titulo: "El río entre el caos y la rigidez", minutos: 5.4 },
      { titulo: "Ponle nombre para domarlo", minutos: 5.3 },
      { titulo: "El encanto de una resonancia magnética", minutos: 5.1 },
      { titulo: "La cara que deja de responder", minutos: 5 },
    ],
  },
  {
    id: "lenguajes-amor",
    titulo: "Los cinco lenguajes del amor",
    autor: "Gary Chapman",
    ano: 1992,
    gancho: "Un pastor baptista de Carolina del Norte releyó veinte años de notas de sus sesiones de pareja, agrupó las quejas en cinco categorías y escribió el libro sobre relaciones más vendido del mundo.",
    porQue: "Porque veinte millones de personas organizan su vida de pareja con este esquema, y porque su afirmación central —que hay que emparejar los lenguajes— es la única comprobable y no ha salido bien de las comprobaciones.",
    minutos: 21.8,
    capitulos: [
      { titulo: "Las notas de un pastor de Winston-Salem", minutos: 4.5 },
      { titulo: "El depósito vacío", minutos: 4.4 },
      { titulo: "Los cinco", minutos: 4.2 },
      { titulo: "Lo que dicen los estudios", minutos: 4.2 },
      { titulo: "La dieta equilibrada", minutos: 4.5 },
    ],
  },
  {
    id: "cosas-buenas",
    titulo: "Cómo hacer que te pasen cosas buenas",
    autor: "Marian Rojas Estapé",
    ano: 2018,
    gancho: "Es probablemente el libro de divulgación más vendido en España en lo que va de siglo, y repite en cada capítulo una frase que es falsa tal y como está escrita.",
    porQue: "Porque su capítulo sobre el estrés crónico está bien y es útil, y porque su neurociencia de cuatro hormonas es una versión de manual popular que conviene saber leer con distancia.",
    minutos: 21.9,
    capitulos: [
      { titulo: "La hija del psiquiatra", minutos: 4.1 },
      { titulo: "El oso que no está", minutos: 4.7 },
      { titulo: "El circuito de la recompensa", minutos: 4.2 },
      { titulo: "Personas vitamina", minutos: 4.5 },
      { titulo: "La psiquiatra que dice que vayas al psiquiatra", minutos: 4.4 },
    ],
  },
  {
    id: "arte-de-amar",
    titulo: "El arte de amar",
    autor: "Erich Fromm",
    ano: 1956,
    gancho: "Ciento treinta páginas escritas en unos meses que han vendido más de veinticinco millones de ejemplares, y de las que su autor llegó a decir que se sentía casi avergonzado.",
    porQue: "Porque su tesis —que amar es una capacidad que se aprende y no una suerte que ocurre— sigue siendo la más útil que se ha escrito sobre el asunto, y porque el capítulo sobre madres y padres envejeció fatal.",
    minutos: 21.6,
    capitulos: [
      { titulo: "La chica que quiso ser enterrada con su padre", minutos: 4.5 },
      { titulo: "El problema no es encontrar a alguien", minutos: 4.6 },
      { titulo: "Cuidado, responsabilidad, respeto, conocimiento", minutos: 4.2 },
      { titulo: "El egoísta no se quiere nada", minutos: 4.2 },
      { titulo: "El libro que le dio vergüenza", minutos: 4.2 },
    ],
  },
  {
    id: "marte-venus",
    titulo: "Los hombres son de Marte, las mujeres son de Venus",
    autor: "John Gray",
    ano: 1992,
    gancho: "Cincuenta millones de ejemplares vendidos sobre una teoría que la investigación no sostiene. Y aun así, mucha gente dice que le salvó la relación.",
    porQue: "Porque la pregunta buena no es si acierta, sino por qué funciona un libro que se equivoca. Contestarla enseña más sobre parejas que el propio libro, y de paso deja lo que sí está medido, que existe y casi nadie conoce.",
    minutos: 24.2,
    capitulos: [
      { titulo: "Un seminario en California", minutos: 4.3 },
      { titulo: "La cueva, la ola y la goma elástica", minutos: 5.1 },
      { titulo: "Lo que dicen los datos sobre las diferencias", minutos: 4.7 },
      { titulo: "Por qué funciona un libro que se equivoca", minutos: 5.1 },
      { titulo: "El apartamento con cámaras de Seattle", minutos: 5 },
    ],
  },
  {
    id: "error-descartes",
    titulo: "El error de Descartes",
    autor: "Antonio Damasio",
    ano: 1994,
    gancho: "Una barra de hierro le atravesó la cabeza a un obrero en 1848. Sobrevivió, conservó la inteligencia entera, y dejó de ser capaz de decidir nada.",
    porQue: "Es el libro que demostró que sin emociones no se razona peor: no se razona. Y lo demostró con pacientes reales a los que todos los tests daban por sanos mientras se les hundía la vida.",
    minutos: 22.6,
    capitulos: [
      { titulo: "Cavendish, Vermont, 13 de septiembre de 1848", minutos: 4.6 },
      { titulo: "El paciente Elliot", minutos: 4.4 },
      { titulo: "La apuesta de las cartas", minutos: 4.3 },
      { titulo: "El marcador somático", minutos: 4.7 },
      { titulo: "El cráneo del museo de Harvard", minutos: 4.5 },
    ],
  },
  {
    id: "intro-psicoanalisis",
    titulo: "Introducción al psicoanálisis",
    autor: "Sigmund Freud",
    ano: 1917,
    gancho: "Veintiocho clases en las que un médico vienés intenta convencer a una sala llena de escépticos de que no somos dueños de nuestra propia cabeza.",
    porQue: "Es Freud explicándose a sí mismo para gente que no sabe nada, y por eso es la puerta de entrada. También es el sitio donde se ve mejor qué se sostiene de todo aquello y qué no.",
    minutos: 22.6,
    capitulos: [
      { titulo: "El anfiteatro de la Universidad de Viena", minutos: 4.6 },
      { titulo: "Los actos fallidos", minutos: 4.5 },
      { titulo: "El taller de los sueños", minutos: 4.4 },
      { titulo: "El diván de Berggasse 19", minutos: 4.5 },
      { titulo: "La casa de Maresfield Gardens", minutos: 4.5 },
    ],
  },
  {
    id: "maneras-de-amar",
    titulo: "Maneras de amar",
    autor: "Levine y Heller",
    ano: 2010,
    gancho: "Las cifras que hoy repite medio internet —la mitad de la gente es segura, un cuarto evitativa, un quinto ansiosa— salen de un cuestionario que dos psicólogos publicaron en un periódico de Denver en 1985 y que los lectores contestaron por correo.",
    porQue: "Porque explica por qué la pareja que te vuelve loco te parece más intensa que la que te trata bien, y porque su vocabulario se ha convertido en un horóscopo de tres casillas que el propio libro no defiende.",
    minutos: 27,
    capitulos: [
      { titulo: "Un cuestionario en un periódico de Denver", minutos: 5.5 },
      { titulo: "Qué hace cada uno cuando tiene miedo", minutos: 5.4 },
      { titulo: "La trampa", minutos: 5.4 },
      { titulo: "Lo que este libro no puede demostrar", minutos: 5.2 },
      { titulo: "Depender bien", minutos: 5.5 },
    ],
  },
  {
    id: "sentirse-bien",
    titulo: "Sentirse bien",
    autor: "David D. Burns",
    ano: 1980,
    gancho: "Es el único libro de autoayuda que se ha probado en ensayos clínicos como si fuera un medicamento. Y salió bien. Lo raro es que su autor acabó publicando datos contra la teoría que lo sostiene.",
    porQue: "Porque es el manual que puso la terapia cognitiva en manos de cualquiera, con un lápiz y una hoja de tres columnas. Y porque su historia enseña algo que casi ningún libro cuenta: que un ejercicio puede funcionar aunque la explicación de por qué funciona sea falsa.",
    minutos: 25.5,
    capitulos: [
      { titulo: "El residente que quería darle la razón a Freud", minutos: 5 },
      { titulo: "Las diez trampas del cuaderno", minutos: 5.1 },
      { titulo: "Tres columnas y un lápiz", minutos: 5.3 },
      { titulo: "Lo que dijeron los ensayos", minutos: 5.2 },
      { titulo: "Lo que queda cuando se cae la teoría", minutos: 4.9 },
    ],
  },
  {
    id: "cero-a-uno",
    titulo: "De cero a uno",
    autor: "Peter Thiel",
    ano: 2014,
    gancho: "Empezó como los apuntes que un estudiante colgó en internet. La primera pregunta del curso era: dime una verdad importante en la que casi nadie te dé la razón.",
    porQue: "Es el libro de startups más citado y el más contrario al consenso: sostiene que competir es de perdedores y que el objetivo de una empresa es el monopolio.",
    minutos: 21.2,
    capitulos: [
      { titulo: "La pregunta contraria", minutos: 4 },
      { titulo: "La competencia es para perdedores", minutos: 4.1 },
      { titulo: "La ley de potencias", minutos: 4.7 },
      { titulo: "El secreto que nadie más ve", minutos: 4.1 },
      { titulo: "Los coches voladores que no llegaron", minutos: 4.4 },
    ],
  },
  {
    id: "lean-startup",
    titulo: "El método Lean Startup",
    autor: "Eric Ries",
    ano: 2011,
    gancho: "Tardaron seis meses en construir su primer producto, lo lanzaron y no lo descargó nadie. El fundador dice que fue lo mejor que le pasó, porque lo peor habría sido tardar dos años.",
    porQue: "Porque de aquí salieron las tres palabras que se dicen hoy en cualquier oficina —producto mínimo viable, pivotar, iterar— y casi todo el mundo las usa mal, empezando por la primera.",
    minutos: 22.2,
    capitulos: [
      { titulo: "El primer producto que nadie descargó", minutos: 4.5 },
      { titulo: "La cuerda que para la cadena", minutos: 4.4 },
      { titulo: "El vídeo de Dropbox", minutos: 4.5 },
      { titulo: "Pivotar o perseverar", minutos: 4.6 },
      { titulo: "Lo que no se puede iterar", minutos: 4.1 },
    ],
  },
  {
    id: "riqueza-naciones",
    titulo: "La riqueza de las naciones",
    autor: "Adam Smith",
    ano: 1776,
    gancho: "Todo el mundo lo cita para defender el mercado sin trabas. Lo escribió un profesor de moral que desconfiaba de los empresarios y pedía escuelas públicas.",
    porQue: "Es el libro que fundó la economía y el más tergiversado de todos. La mano invisible aparece una sola vez en mil páginas, y no significa lo que se repite en las tertulias.",
    minutos: 23.2,
    capitulos: [
      { titulo: "La fábrica de alfileres", minutos: 4.9 },
      { titulo: "El carnicero, el cervecero y el panadero", minutos: 4.8 },
      { titulo: "Una conspiración contra el público", minutos: 4.5 },
      { titulo: "La escuela de la parroquia", minutos: 4.5 },
      { titulo: "La aduana de Edimburgo", minutos: 4.4 },
    ],
  },
  {
    id: "por-que-fracasan",
    titulo: "Por qué fracasan los países",
    autor: "Acemoglu y Robinson",
    ano: 2012,
    gancho: "Dos ciudades con el mismo nombre, separadas por una valla: al norte se vive tres veces mejor.",
    porQue: "Es el libro que cambió la conversación sobre por qué unos países son ricos y otros no: la respuesta no está en el clima ni en la cultura, sino en quién manda y con qué reglas. Sus autores recibieron el Nobel de Economía en 2024.",
    minutos: 23.4,
    capitulos: [
      { titulo: "La valla de Nogales", minutos: 4.8 },
      { titulo: "Potosí y Jamestown", minutos: 4.7 },
      { titulo: "El telar que la reina no quiso", minutos: 4.7 },
      { titulo: "1688", minutos: 4.5 },
      { titulo: "Pekín", minutos: 4.7 },
    ],
  },
  {
    id: "doctrina-shock",
    titulo: "La doctrina del shock",
    autor: "Naomi Klein",
    ano: 2007,
    gancho: "Su tesis es que las reformas que nadie votaría se aprueban en los días en que la gente está demasiado aturdida para discutirlas. Documenta cuarenta años de ejemplos.",
    porQue: "Es el libro que puso nombre a algo que se ve cada vez que hay una catástrofe. Y es también un caso de estudio perfecto de cómo se lee un libro de tesis fuerte: separando lo que documenta de lo que solo insinúa, que aquí son dos cosas muy distintas.",
    minutos: 25.3,
    capitulos: [
      { titulo: "Un sótano de Montreal", minutos: 4.4 },
      { titulo: "El primer laboratorio fue Chile", minutos: 5.6 },
      { titulo: "Cuando la crisis llega sola", minutos: 5.5 },
      { titulo: "Bagdad, Nueva Orleans y una playa de Sri Lanka", minutos: 5.5 },
      { titulo: "Lo que demuestra y lo que solo insinúa", minutos: 4.3 },
    ],
  },
  {
    id: "millonario-al-lado",
    titulo: "El millonario de al lado",
    autor: "Stanley y Danko",
    ano: 1996,
    gancho: "Un profesor de marketing montó una degustación de lujo para diez millonarios y ninguno tocó el foie. Uno le pidió una cerveza y le dijo que solo bebía dos marcas: la gratis y la barata.",
    porQue: "Porque separa dos cosas que casi todo el mundo confunde y que cuestan mucho dinero confundir: cobrar mucho y ser rico. Y porque su fórmula famosa no sale, y su método tiene el problema que Taleb lleva veinte años denunciando.",
    minutos: 25.6,
    capitulos: [
      { titulo: "Una degustación que nadie tocó", minutos: 5.2 },
      { titulo: "La camioneta del millonario", minutos: 5.1 },
      { titulo: "La fórmula que no sale", minutos: 5.1 },
      { titulo: "El cementerio que no se encuestó", minutos: 5.1 },
      { titulo: "Renta no es riqueza", minutos: 5.1 },
    ],
  },
  {
    id: "paseo-aleatorio",
    titulo: "Un paseo aleatorio por Wall Street",
    autor: "Burton Malkiel",
    ano: 1973,
    gancho: "Un mono con los ojos vendados tirando dardos a las páginas de bolsa elige una cartera tan buena como la de los expertos. Lleva cincuenta años sin que nadie lo desmienta del todo.",
    porQue: "Es el libro que explica por qué casi todo lo que se cobra por gestionar tu dinero no vale lo que cuesta, y lo demuestra con datos en vez de con indignación. Sirve igual para invertir que para desconfiar de cualquiera que prometa predecir el futuro.",
    minutos: 23.1,
    capitulos: [
      { titulo: "El mono con los ojos vendados", minutos: 4.5 },
      { titulo: "Tulipanes, mares del Sur y puntocom", minutos: 4.8 },
      { titulo: "Las dos maneras de fallar el pronóstico", minutos: 4.5 },
      { titulo: "Lo único que está en tu mano", minutos: 4.6 },
      { titulo: "Dónde cojea el paseo aleatorio", minutos: 4.7 },
    ],
  },
  {
    id: "repensar-pobreza",
    titulo: "Repensar la pobreza",
    autor: "Banerjee y Duflo",
    ano: 2011,
    gancho: "Una familia que no come suficiente se gasta el dinero en un televisor. El libro que se tomó en serio esa decisión ganó el Nobel de Economía.",
    porQue: "Es el libro que cambió la manera de repartir la ayuda al desarrollo, sustituyendo las grandes teorías por experimentos con grupo de control. Y su hallazgo central es que los pobres no se equivocan: deciden bien en condiciones que nosotros no tenemos.",
    minutos: 23.2,
    capitulos: [
      { titulo: "Un pueblo de Udaipur, Rajastán", minutos: 4.7 },
      { titulo: "La trampa del hambre", minutos: 4.7 },
      { titulo: "Los tres litros de cloro", minutos: 4.3 },
      { titulo: "La escuela sin maestro", minutos: 4.4 },
      { titulo: "Estocolmo, diciembre de 2019", minutos: 5 },
    ],
  },
  {
    id: "bogle-sentido-comun",
    titulo: "El pequeño libro para invertir con sentido común",
    autor: "John C. Bogle",
    ano: 2007,
    gancho: "Su fondo salió a bolsa en 1976 buscando ciento cincuenta millones y recaudó once. Lo llamaron la locura de Bogle. Cuarenta años después esa idea maneja billones y su inventor murió avisando de que se le había ido de las manos.",
    porQue: "Porque contiene el único argumento de inversión que se demuestra con una resta y no con una predicción. Y porque separar lo que Bogle demostró de lo que se le atribuye enseña a leer cualquier consejo financiero que te pongan delante.",
    minutos: 26.2,
    capitulos: [
      { titulo: "La locura de Bogle", minutos: 5.2 },
      { titulo: "La aritmética implacable", minutos: 5.3 },
      { titulo: "Los datos que le dieron la razón", minutos: 5.1 },
      { titulo: "Lo que el libro no cuenta", minutos: 5.3 },
      { titulo: "La advertencia que dejó escrita", minutos: 5.2 },
    ],
  },
  {
    id: "superpronosticadores",
    titulo: "Superpronosticadores",
    autor: "Philip E. Tetlock y Dan Gardner",
    ano: 2015,
    gancho: "Un psicólogo apuntó durante veinte años los pronósticos de 284 expertos y los corrigió como un examen. El experto medio acertaba menos que una regla tonta.",
    porQue: "Es el único libro que trata la predicción como algo medible en vez de como una opinión con traje. Y de ahí saca hábitos concretos que se pueden usar mañana: partir la pregunta, empezar por la frecuencia base y corregir poco a poco.",
    minutos: 24.4,
    capitulos: [
      { titulo: "Veinte años apuntando aciertos", minutos: 4.7 },
      { titulo: "El torneo que pagó el espionaje", minutos: 4.9 },
      { titulo: "Cómo piensan los que aciertan", minutos: 5.1 },
      { titulo: "Dónde deja de funcionar", minutos: 4.8 },
      { titulo: "Llevar la cuenta", minutos: 4.8 },
    ],
  },
  {
    id: "dinero-domina-juego",
    titulo: "Dinero: domina el juego",
    autor: "Tony Robbins",
    ano: 2014,
    gancho: "Un conferenciante motivacional sin ningún título financiero consiguió sentarse con cincuenta de los mayores inversores del mundo, entre ellos Buffett, Dalio y el fundador de Vanguard, y les preguntó lo que preguntaría cualquiera. Lo que le contestaron ocupa seiscientas páginas y no siempre le conviene.",
    porQue: "Porque su capítulo sobre comisiones es de lo mejor que se ha escrito para el público general, y porque el mismo libro que demuestra que las comisiones te arruinan te acaba mandando a una firma de asesoramiento en la que el autor tenía participación.",
    minutos: 27.2,
    capitulos: [
      { titulo: "Cincuenta entrevistas y una libreta", minutos: 5.2 },
      { titulo: "El uno por ciento que se lleva un tercio", minutos: 5.5 },
      { titulo: "La cartera de todas las estaciones", minutos: 5.5 },
      { titulo: "Quién cobra cuando sigues el consejo", minutos: 5.4 },
      { titulo: "Las tres frases que sobreviven", minutos: 5.5 },
    ],
  },
  {
    id: "outlive",
    titulo: "Outlive: el arte de vivir más y mejor",
    autor: "Peter Attia",
    ano: 2023,
    gancho: "Un cirujano que odiaba la medicina preventiva calcula cuántos años de vida sana pierde el que espera a tener síntomas. Le salen veinte.",
    porQue: "Es el libro de longevidad con la mejor argumentación y también el que más honradamente admite dónde no hay pruebas. Y el consejo principal no es la dieta.",
    minutos: 22,
    capitulos: [
      { titulo: "El paciente que llega tarde", minutos: 4.5 },
      { titulo: "Los cuatro jinetes", minutos: 4.3 },
      { titulo: "VO2 máx", minutos: 4.5 },
      { titulo: "El decatlón del centenario", minutos: 4.5 },
      { titulo: "El paciente difícil", minutos: 4.2 },
    ],
  },
  {
    id: "nacidos-correr",
    titulo: "Nacidos para correr",
    autor: "Christopher McDougall",
    ano: 2009,
    gancho: "Fue al médico porque le dolía el pie corriendo. Acabó en un cañón de México con gente que corre cien kilómetros con sandalias de neumático.",
    porQue: "Cambió la manera de correr y de fabricar zapatillas de medio mundo a partir de una pregunta. Y después llegaron los ensayos clínicos y una demanda judicial.",
    minutos: 25.8,
    capitulos: [
      { titulo: "¿Por qué me duele el pie?", minutos: 5.2 },
      { titulo: "Los de los pies ligeros", minutos: 5.1 },
      { titulo: "El simio que suda", minutos: 5.2 },
      { titulo: "La carrera de 2006", minutos: 5.1 },
      { titulo: "La demanda de las zapatillas", minutos: 5.2 },
    ],
  },
  {
    id: "dilema-omnivoro",
    titulo: "El dilema del omnívoro",
    autor: "Michael Pollan",
    ano: 2006,
    gancho: "Siguió cuatro comidas hasta su origen. Una de ellas venía casi entera de una sola planta: el maíz.",
    porQue: "Es el libro que cambió la conversación pública sobre comida, y conviene saber qué demostró y qué solo insinuó.",
    minutos: 26,
    capitulos: [
      { titulo: "El pasillo del supermercado", minutos: 5.2 },
      { titulo: "El mar de maíz de Iowa", minutos: 5.2 },
      { titulo: "La etiqueta que dice ecológico", minutos: 5.2 },
      { titulo: "La hierba de Polyface", minutos: 5.2 },
      { titulo: "La cena que se cazó él mismo", minutos: 5.1 },
    ],
  },
  {
    id: "milagro-manana",
    titulo: "Mañanas milagrosas",
    autor: "Hal Elrod",
    ano: 2012,
    gancho: "Estuvo clínicamente muerto seis minutos a los veinte años. Doce años después escribió un método de una hora que han copiado dos millones de personas.",
    porQue: "Porque cuatro de sus seis prácticas están razonablemente respaldadas, y la afirmación central del libro sobre el sueño es sencillamente falsa.",
    minutos: 21.7,
    capitulos: [
      { titulo: "Seis minutos muerto", minutos: 4.4 },
      { titulo: "Las seis prácticas", minutos: 4.3 },
      { titulo: "No se negocia con el sueño", minutos: 4.6 },
      { titulo: "Los treinta primeros días", minutos: 4.1 },
      { titulo: "La hora que no importa", minutos: 4.2 },
    ],
  },
  {
    id: "come-comida-real",
    titulo: "Come comida real",
    autor: "Carlos Ríos",
    ano: 2019,
    gancho: "Siete de cada diez productos de un supermercado español no son comida en sentido estricto. Son formulaciones industriales diseñadas para que no puedas parar.",
    porQue: "Porque detrás del eslogan hay un ensayo clínico de 2019 que es de los pocos experimentos serios que existen en nutrición, y sus resultados son difíciles de discutir.",
    minutos: 20.6,
    capitulos: [
      { titulo: "El setenta por ciento del supermercado", minutos: 4.1 },
      { titulo: "Dos semanas encerrados", minutos: 4.1 },
      { titulo: "La lista de ingredientes", minutos: 4 },
      { titulo: "Lo que cuesta cocinar", minutos: 4.2 },
      { titulo: "La cocina de un martes", minutos: 4.2 },
    ],
  },
  {
    id: "invencible",
    titulo: "Invicto",
    autor: "Marcos Vázquez",
    ano: 2021,
    gancho: "El mismo principio que hace crecer un músculo —estrés controlado más descanso— aplicado a la cabeza. Con dos mil años de instrucciones ya escritas.",
    porQue: "Es la mejor traducción al español del estoicismo a un programa de entrenamiento, y también un buen sitio para ver dónde ese marco deja de funcionar.",
    minutos: 21,
    capitulos: [
      { titulo: "El esclavo cojo", minutos: 4.1 },
      { titulo: "Lo que depende de ti", minutos: 4.2 },
      { titulo: "Sobrecarga progresiva", minutos: 4.1 },
      { titulo: "El juez interior", minutos: 4.2 },
      { titulo: "Amor fati", minutos: 4.5 },
    ],
  },
  {
    id: "zonas-azules",
    titulo: "El secreto de las zonas azules",
    autor: "Dan Buettner",
    ano: 2008,
    gancho: "Cinco sitios del mundo donde la gente llega a los cien años. Y una pregunta incómoda que llegó quince años después: ¿y si muchos no los tuvieran?",
    porQue: "Es el libro que metió el ikigai y la dieta mediterránea en medio mundo, y también el mejor caso práctico de cómo se convierte una correlación en un negocio.",
    minutos: 22.3,
    capitulos: [
      { titulo: "El círculo azul en el mapa", minutos: 4.4 },
      { titulo: "Los pastores de Cerdeña", minutos: 4.5 },
      { titulo: "El moai de Okinawa", minutos: 4.6 },
      { titulo: "El plan de vida", minutos: 4.4 },
      { titulo: "Los papeles", minutos: 4.4 },
    ],
  },
  {
    id: "anticancer",
    titulo: "Anticáncer",
    autor: "David Servan-Schreiber",
    ano: 2007,
    gancho: "Un neurocientífico de treinta y un años se metió en su propio escáner para sustituir a un voluntario que no vino. Le encontraron un tumor cerebral.",
    porQue: "Es el libro sobre cáncer y estilo de vida más vendido de este siglo, escrito por un médico serio que además era el paciente. Merece leerse separando con cuidado lo que la evidencia sostiene de lo que él quería que fuera verdad.",
    minutos: 22.2,
    capitulos: [
      { titulo: "El escáner de Pittsburgh, 1992", minutos: 4.5 },
      { titulo: "La cocina", minutos: 4.5 },
      { titulo: "El gimnasio y la respiración", minutos: 4.2 },
      { titulo: "El informe del Fondo Mundial", minutos: 4.7 },
      { titulo: "El 24 de julio de 2011", minutos: 4.3 },
    ],
  },
  {
    id: "codigo-obesidad",
    titulo: "El código de la obesidad",
    autor: "Jason Fung",
    ano: 2016,
    gancho: "Un nefrólogo de Toronto llevaba años poniendo diálisis a diabéticos y un día se dio cuenta de que estaba tratando las complicaciones de una enfermedad que, según él, se podía revertir.",
    porQue: "Porque acierta en cosas que la nutrición oficial llevaba treinta años diciendo mal, y porque su mecanismo central se ha puesto a prueba en salas metabólicas después de 2016 y no ha salido bien parado.",
    minutos: 23.4,
    capitulos: [
      { titulo: "El nefrólogo que se hartó", minutos: 4.5 },
      { titulo: "Los treinta y seis hombres de Minnesota", minutos: 4.6 },
      { titulo: "La hormona que guarda", minutos: 4.5 },
      { titulo: "Cuándo comes", minutos: 4.4 },
      { titulo: "La sala metabólica de Kevin Hall", minutos: 5.4 },
    ],
  },
  {
    id: "dieta-cojea",
    titulo: "Mi dieta cojea",
    autor: "Aitor Sánchez García",
    ano: 2016,
    gancho: "En 2015, la pirámide alimentaria oficial española tenía cerveza y vino dentro, y estaba patrocinada, entre otros, por fabricantes de bollería y de bebidas alcohólicas.",
    porQue: "Porque es el libro que puso nombre en español a las mentiras que hay en cualquier supermercado, y porque su parte más útil —qué comer— es la más corta.",
    minutos: 23,
    capitulos: [
      { titulo: "El nutricionista que no estaba en el ambulatorio", minutos: 4.3 },
      { titulo: "La pirámide con cerveza dentro", minutos: 4.6 },
      { titulo: "El desayuno completo", minutos: 4.7 },
      { titulo: "Grupo uno no significa lo que crees", minutos: 4.6 },
      { titulo: "Vale, ¿y entonces qué como?", minutos: 4.8 },
    ],
  },
  {
    id: "milagro-metabolico",
    titulo: "El milagro metabólico",
    autor: "Carlos Jaramillo",
    ano: 2019,
    gancho: "Sostiene que el problema no son las calorías sino las hormonas. Acierta en la crítica al modelo viejo y se pasa de frenada al sustituirlo por una sola causa.",
    porQue: "Es el libro de salud más vendido en español de los últimos años y tiene una mitad sólida y otra que no se sostiene. Separarlas enseña a leer cualquier libro de nutrición, que es lo más útil que se puede sacar de este estante.",
    minutos: 23.4,
    capitulos: [
      { titulo: "Una consulta en Bogotá", minutos: 4.7 },
      { titulo: "Lo que sí está respaldado", minutos: 4.8 },
      { titulo: "La hipótesis de la insulina", minutos: 4.6 },
      { titulo: "El ayuno y el resto del botiquín", minutos: 4.8 },
      { titulo: "Cómo se lee un libro de salud", minutos: 4.5 },
    ],
  },
  {
    id: "cerebro-de-pan",
    titulo: "Cerebro de pan",
    autor: "David Perlmutter",
    ano: 2013,
    gancho: "Un neurólogo sostiene que el pan, la pasta y la fruta te están destruyendo el cerebro, y que el alzhéimer es una diabetes. Ha vendido millones de ejemplares.",
    porQue: "Es de los libros de salud más vendidos del siglo y conviene leerlo con la evidencia al lado, porque cita estudios reales y saca de ellos conclusiones que los estudios no dicen. Aprender a ver esa costura sirve para cualquier libro del estante.",
    minutos: 24.9,
    capitulos: [
      { titulo: "Una consulta en Naples, Florida", minutos: 4.8 },
      { titulo: "El uno por ciento que sí", minutos: 5.5 },
      { titulo: "El experimento de Melbourne", minutos: 5.4 },
      { titulo: "La diabetes tipo tres", minutos: 4.7 },
      { titulo: "El pasillo de los suplementos", minutos: 4.5 },
    ],
  },
  {
    id: "vivir-plenitud",
    titulo: "Vivir con plenitud las crisis",
    autor: "Jon Kabat-Zinn",
    ano: 1990,
    gancho: "Un biólogo molecular montó en el sótano de un hospital una consulta para los pacientes que ya no mejoraban, y les enseñó a comerse una uva pasa.",
    porQue: "Es el manual del programa del que salió todo el mindfulness que hay hoy en hospitales, aplicaciones y oficinas. Merece la pena leer el original para ver qué prometía de verdad y qué le han colgado después.",
    minutos: 23.9,
    capitulos: [
      { titulo: "El sótano de Worcester", minutos: 4.9 },
      { titulo: "Una uva pasa", minutos: 5.1 },
      { titulo: "Cuarenta y cinco minutos tumbado", minutos: 4.7 },
      { titulo: "La consulta del dermatólogo", minutos: 4.6 },
      { titulo: "La sala de reuniones de Google", minutos: 4.7 },
    ],
  },
  {
    id: "deja-de-ser-tu",
    titulo: "Deja de ser tú",
    autor: "Joe Dispenza",
    ano: 2012,
    gancho: "Un quiropráctico se rompió seis vértebras en 1986, rechazó la operación y se pasó dos meses y medio boca abajo reconstruyendo su columna con la imaginación. Volvió a andar, y de ahí sale todo lo demás.",
    porQue: "Porque llena estadios en español y merece un examen serio en vez de una burla. Debajo hay una hora de meditación diaria que es defendible, una neurociencia real estirada hasta romperse y una física cuántica que dice justo lo contrario de lo que él cuenta.",
    minutos: 25.1,
    capitulos: [
      { titulo: "Una bicicleta en Palm Springs", minutos: 5.1 },
      { titulo: "Las neuronas que se disparan juntas", minutos: 5 },
      { titulo: "El campo cuántico", minutos: 5.1 },
      { titulo: "La culpa de estar enfermo", minutos: 4.8 },
      { titulo: "Una hora sentado antes de que amanezca", minutos: 5.1 },
    ],
  },
  {
    id: "poder-metabolismo",
    titulo: "El poder del metabolismo",
    autor: "Frank Suárez",
    ano: 2006,
    gancho: "El libro de salud más vendido en español lo escribió alguien sin ninguna titulación sanitaria, que vendía los suplementos que recomendaba. Y aun así acertó en la cosa que la medicina tardó otros diez años en admitir.",
    porQue: "Porque separar en este libro lo que funciona de lo que está inventado es el mejor ejercicio de lectura crítica que se puede hacer en salud. Y porque millones de personas en español lo usaron: merecen que alguien haga esa separación en serio, sin reírse de ellas.",
    minutos: 25.4,
    capitulos: [
      { titulo: "Un hombre de ciento treinta kilos con una libreta", minutos: 5 },
      { titulo: "Dos tipos de sistema nervioso que no existen", minutos: 5.2 },
      { titulo: "El plato partido en dos tercios", minutos: 5.3 },
      { titulo: "La tienda que hay detrás del libro", minutos: 4.9 },
      { titulo: "Lo que sí se le rompe a un cuerpo que ha hecho veinte dietas", minutos: 5.1 },
    ],
  },
];

/** Índice por identificador, que es como lo pide la pantalla. */
export const META_POR_ID: Record<string, FichaMeta> = Object.fromEntries(
  META.map((f) => [f.id, f]),
);
