/* ==========================================================================
   GENERADO por scripts/generar-meta.mjs — no editar a mano.

   Lo mínimo que hace falta para pintar la biblioteca sin descargar el texto
   de los libros: título, autor, año, las dos frases de la ficha y los minutos
   de cada capítulo, que son los que se ven parada por parada en el mapa del
   camino. El texto entero se pide aparte, al abrir un libro.

   Para regenerarlo:  npx tsx scripts/generar-meta.mjs
   ========================================================================== */

export type CapituloMeta = { titulo: string; minutos: number };

export type FichaMeta = {
  id: string;
  titulo: string;
  autor: string;
  ano: number;
  gancho: string;
  porQue: string;
  minutos: number;
  capitulos: CapituloMeta[];
};

export const META: FichaMeta[] = [
  {
    id: "canones-agosto",
    titulo: "Los cañones de agosto",
    autor: "Barbara Tuchman",
    ano: 1962,
    gancho: "Un solo mes de 1914 contado en quinientas páginas. Kennedy lo leyó y lo repartió entre su gabinete justo antes de la crisis de los misiles de Cuba.",
    porQue: "Es el mejor libro que existe sobre cómo unos hombres razonables, con buenos planes, meten a un continente entero en una catástrofe en treinta días.",
    minutos: 21.3,
    capitulos: [
      { titulo: "Nueve reyes a caballo", minutos: 4.3 },
      { titulo: "El plan de un hombre muerto", minutos: 4.2 },
      { titulo: "Bélgica", minutos: 4.2 },
      { titulo: "El día más sangriento de Francia", minutos: 4.3 },
      { titulo: "El despacho de Kennedy", minutos: 4.4 },
    ],
  },
  {
    id: "tatuador",
    titulo: "El tatuador de Auschwitz",
    autor: "Heather Morris",
    ano: 2018,
    gancho: "Un hombre de ochenta y siete años que llevaba cincuenta callado, porque temía que si contaba lo que hizo en Auschwitz lo tomaran por colaborador.",
    porQue: "Porque ha vendido más de ocho millones de ejemplares y es, para mucha gente, su única idea de cómo era Auschwitz. Y porque el propio Museo de Auschwitz publicó un informe enumerando lo que tiene de falso.",
    minutos: 20.9,
    capitulos: [
      { titulo: "El número 32407", minutos: 4.3 },
      { titulo: "El hombre que marcaba brazos", minutos: 4.1 },
      { titulo: "34902", minutos: 4.1 },
      { titulo: "Los diamantes en el dobladillo", minutos: 4.1 },
      { titulo: "Melbourne, 2003", minutos: 4.4 },
    ],
  },
  {
    id: "guerra-civil-thomas",
    titulo: "La guerra civil española",
    autor: "Hugh Thomas",
    ano: 1961,
    gancho: "Un inglés de veintinueve años escribió la primera historia completa de la guerra de España. En España estuvo prohibida y entró de contrabando en maletas.",
    porQue: "Durante quince años fue el único libro donde un español podía leer lo que había pasado en su propio país. Hoy está superado en casi todo, y sigue siendo el mejor sitio para entender la guerra entera de una vez.",
    minutos: 23.4,
    capitulos: [
      { titulo: "Un funcionario que dimite por Suez", minutos: 4.9 },
      { titulo: "El 17 de julio de 1936", minutos: 4.7 },
      { titulo: "El Comité de No Intervención, Londres", minutos: 4.7 },
      { titulo: "El Ebro", minutos: 4.5 },
      { titulo: "Ruedo Ibérico, París, 1962", minutos: 4.6 },
    ],
  },
  {
    id: "auschwitz-rees",
    titulo: "Auschwitz: los nazis y la solución final",
    autor: "Laurence Rees",
    ano: 2005,
    gancho: "En mayo de 1940, el sitio era un cuartel abandonado en un pueblo polaco de doce mil habitantes y estaba pensado para presos políticos polacos. Nadie que estuviera allí aquel día había planeado lo que vendría después, y ese es exactamente el argumento del libro.",
    porQue: "Porque explica, paso a paso y con fechas, cómo se llegó hasta allí sin que exista una sola orden firmada; y porque corrige de raíz las dos cosas que casi todo el mundo cree: la cifra de la placa y la idea de que Auschwitz es donde murió la mayoría.",
    minutos: 26.9,
    capitulos: [
      { titulo: "Un cuartel de artillería en un pueblo polaco", minutos: 5.4 },
      { titulo: "Nadie encontró la orden firmada", minutos: 5.4 },
      { titulo: "La cifra de la placa", minutos: 5.3 },
      { titulo: "Los que intentaron pararlo", minutos: 5.3 },
      { titulo: "El contable que se sentó delante de la cámara", minutos: 5.5 },
    ],
  },
  {
    id: "postguerra",
    titulo: "Postguerra",
    autor: "Tony Judt",
    ano: 2005,
    gancho: "Europa en 1945 era un continente de escombros, hambre y treinta millones de muertos. Cómo salió de ahí es la mejor historia que se ha escrito de nuestro propio siglo.",
    porQue: "Explica de dónde salieron el estado del bienestar, la Unión Europea y la Transición española, y por qué nada de eso era inevitable. Y termina con la idea más incómoda del libro: que Europa se reconstruyó sobre un acuerdo de no recordar.",
    minutos: 24.3,
    capitulos: [
      { titulo: "El año cero", minutos: 5.1 },
      { titulo: "Los treinta años que parecieron normales", minutos: 5.6 },
      { titulo: "La mitad que se quedó al otro lado", minutos: 4.3 },
      { titulo: "1968, 1973 y la vuelta del sur", minutos: 4.6 },
      { titulo: "1989 y la deuda con los muertos", minutos: 4.8 },
    ],
  },
  {
    id: "homo-sovieticus",
    titulo: "El fin del Homo Sovieticus",
    autor: "Svetlana Aleksiévich",
    ano: 2013,
    gancho: "Veinte años grabando a gente corriente del imperio que se cayó. Le dieron el Nobel por ello, y también la llevaron a juicio por lo mismo: por lo que hace con las cintas cuando se sienta a escribir.",
    porQue: "Porque es el mejor retrato que existe de lo que le pasa por dentro a un país cuando se le acaba el mundo. Y porque su título original no dice lo que dice el español: no habla de un final, habla de ropa usada que alguien se ha vuelto a poner.",
    minutos: 25.9,
    capitulos: [
      { titulo: "Un mariscal se ahorca en su despacho del Kremlin", minutos: 5.1 },
      { titulo: "Cien horas de grabación para tres páginas", minutos: 5.2 },
      { titulo: "La libertad resultó ser el salchichón", minutos: 5.2 },
      { titulo: "El juicio de Minsk", minutos: 5.1 },
      { titulo: "Tiempo de segunda mano", minutos: 5.2 },
    ],
  },
  {
    id: "imperiofobia",
    titulo: "Imperiofobia y leyenda negra",
    autor: "María Elvira Roca Barea",
    ano: 2016,
    gancho: "Sostiene que España es el único imperio de la historia que se creyó la propaganda de sus enemigos. Vendió cientos de miles de ejemplares y los historiadores profesionales lo destrozaron.",
    porQue: "Porque lleva razón en muchos datos concretos que casi nadie conoce y usa el mismo método que denuncia. Leerlo bien enseña a la vez historia de España y algo más útil: cómo se fabrica el relato que un país se cuenta de sí mismo.",
    minutos: 24.6,
    capitulos: [
      { titulo: "Un panfleto impreso en Delft", minutos: 5 },
      { titulo: "Los datos que casi nadie conoce", minutos: 5.1 },
      { titulo: "Lo que le contestaron los historiadores", minutos: 4.8 },
      { titulo: "Cómo se fabrica el relato de un país", minutos: 4.9 },
      { titulo: "Qué hacer con un libro así", minutos: 4.8 },
    ],
  },
  {
    id: "etica-amador",
    titulo: "Ética para Amador",
    autor: "Fernando Savater",
    ano: 1991,
    gancho: "Un catedrático de filosofía le escribe a su hijo de quince años para explicarle por qué no piensa darle ni una sola norma de conducta.",
    porQue: "Es el libro de filosofía más leído en español del último medio siglo, y su tesis central sigue siendo la más incómoda: portarse bien es un asunto de egoísmo bien entendido.",
    minutos: 22,
    capitulos: [
      { titulo: "Una carta a un hijo de quince años", minutos: 4.4 },
      { titulo: "Las termitas no pueden elegir", minutos: 4.4 },
      { titulo: "Haz lo que quieras", minutos: 4.4 },
      { titulo: "Ponte en su lugar", minutos: 4.3 },
      { titulo: "Lo que respondió Amador", minutos: 4.5 },
    ],
  },
  {
    id: "etica-nicomaco",
    titulo: "Ética a Nicómaco",
    autor: "Aristóteles",
    ano: -340,
    gancho: "El primer manual de cómo vivir. No pregunta qué debes hacer, sino en quién te estás convirtiendo cada vez que lo haces.",
    porQue: "Es el origen de casi todo lo que hoy se dice sobre hábitos, carácter y amistad, y lo dice mejor que sus herederos. Leerlo entero enseña además a distinguir lo que sobrevive de un clásico de lo que caducó con su autor.",
    minutos: 25,
    capitulos: [
      { titulo: "Una escuela a las afueras de Atenas", minutos: 5.2 },
      { titulo: "El término medio no es la mitad", minutos: 5 },
      { titulo: "Se aprende tocando la cítara", minutos: 4.7 },
      { titulo: "Los amigos que hacen falta", minutos: 5.3 },
      { titulo: "La vida que se elige por sí misma", minutos: 4.8 },
    ],
  },
  {
    id: "contrato-social",
    titulo: "El contrato social",
    autor: "Jean-Jacques Rousseau",
    ano: 1762,
    gancho: "Lo quemaron en Ginebra y en París el mismo año de publicarse, y su autor tuvo que huir de tres países. Treinta años después, los revolucionarios franceses llevaron sus restos al Panteón en volandas.",
    porQue: "Porque de aquí sale la idea de que la ley solo obliga si la hemos hecho nosotros, que es el fundamento de cualquier democracia. Y porque casi todo lo que se le atribuye —el buen salvaje, la vuelta a la naturaleza, el gobierno de la mayoría— no está en el libro.",
    minutos: 26.1,
    capitulos: [
      { titulo: "Una frase que todo el mundo cita a medias", minutos: 5.1 },
      { titulo: "El buen salvaje que nunca escribió", minutos: 5.4 },
      { titulo: "La voluntad general no es la mayoría", minutos: 5.2 },
      { titulo: "El pueblo inglés cree ser libre", minutos: 5.2 },
      { titulo: "Los cinco niños del hospicio", minutos: 5.2 },
    ],
  },
  {
    id: "mas-alla-bien-mal",
    titulo: "Más allá del bien y del mal",
    autor: "Friedrich Nietzsche",
    ano: 1886,
    gancho: "Lo pagó de su bolsillo, se imprimieron seiscientos ejemplares y en el primer año vendió poco más de cien. Cuarenta años después, su hermana recibía a Hitler en el archivo donde guardaba sus papeles, con un libro suyo que él nunca escribió.",
    porQue: "Porque es el Nietzsche argumentado, el que explica en prosa lo que Zaratustra decía en parábolas. Y porque el título no significa lo que casi todo el mundo cree que significa: no es una licencia para hacer lo que a uno le dé la gana.",
    minutos: 27.5,
    capitulos: [
      { titulo: "Seiscientos ejemplares pagados de su bolsillo", minutos: 5.3 },
      { titulo: "El filósofo también tiene un cuerpo", minutos: 5.5 },
      { titulo: "Dos maneras de decir bueno", minutos: 5.7 },
      { titulo: "Lo que no se puede lavar", minutos: 5.4 },
      { titulo: "El archivo de Weimar", minutos: 5.6 },
    ],
  },
  {
    id: "existencialismo-humanismo",
    titulo: "El existencialismo es un humanismo",
    autor: "Jean-Paul Sartre",
    ano: 1946,
    gancho: "El texto filosófico más leído del siglo XX es la transcripción de una conferencia que su autor dio sin notas, en una sala donde la gente se desmayaba, y de cuya publicación se arrepintió el resto de su vida.",
    porQue: "Porque de aquí salen las tres frases que todo el mundo cita sobre la libertad. Y porque leerlo entero enseña algo que las frases sueltas ocultan: que no es una filosofía permisiva, sino la más exigente que hay en el estante.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Una sala rota en la rue Jean-Goujon", minutos: 5 },
      { titulo: "Un cortapapeles y un Dios que no está", minutos: 5.1 },
      { titulo: "El chico que no sabía si irse a Londres", minutos: 5.1 },
      { titulo: "La carta que le mandó Heidegger", minutos: 5.1 },
      { titulo: "Lo que Sartre dejó de creer", minutos: 5.2 },
    ],
  },
  {
    id: "ensayos-montaigne",
    titulo: "Ensayos",
    autor: "Michel de Montaigne",
    ano: 1580,
    gancho: "Se encerró en una torre a los treinta y ocho años para escribir sobre el único asunto que conocía de primera mano: él mismo. Inventó de paso un género entero.",
    porQue: "Es el primer libro moderno y sigue siendo el más honrado. Enseña un hábito que no caduca: preguntarle a cada cosa que uno cree si la creería igual habiendo nacido cuarenta leguas más allá.",
    minutos: 25,
    capitulos: [
      { titulo: "Una torre con frases en el techo", minutos: 5 },
      { titulo: "El hombre que se puso a sí mismo de tema", minutos: 5 },
      { titulo: "Contra la crueldad", minutos: 5 },
      { titulo: "La caída del caballo", minutos: 5 },
      { titulo: "Lo que hizo con los que vinieron después", minutos: 5.1 },
    ],
  },
  {
    id: "arte-sin-hombres",
    titulo: "Historia del arte sin hombres",
    autor: "Katy Hessel",
    ano: 2022,
    gancho: "En una feria de arte de Londres con miles de obras no había ni una sola de una mujer. La que se dio cuenta tenía veintiún años y decidió escribir el otro libro.",
    porQue: "Es la respuesta directa al manual de Gombrich, y no va de opinar: va de enseñar los mecanismos concretos por los que media historia del arte desapareció.",
    minutos: 22,
    capitulos: [
      { titulo: "Una feria sin una sola mujer", minutos: 4.4 },
      { titulo: "El juicio de Artemisia", minutos: 4.4 },
      { titulo: "Las dos que solo están en el cuadro", minutos: 4.3 },
      { titulo: "La abstracción llegó antes", minutos: 4.6 },
      { titulo: "¿Hay que estar desnuda?", minutos: 4.3 },
    ],
  },
  {
    id: "van-gogh-cartas",
    titulo: "Cartas a Theo",
    autor: "Vincent van Gogh",
    ano: 1914,
    gancho: "Pintó unas dos mil obras en diez años y solo se le documenta una venta. Su hermano le pagó cada tubo de pintura.",
    porQue: "Las cartas desmontan el mito del loco que pintaba por instinto: era un lector voraz que razonaba cada color. Y existen porque una viuda de veintiocho años decidió que existieran.",
    minutos: 26.6,
    capitulos: [
      { titulo: "El evangelista despedido de las minas", minutos: 5.2 },
      { titulo: "Ciento cincuenta francos al mes", minutos: 5.5 },
      { titulo: "Por qué este rojo va contra este verde", minutos: 5.2 },
      { titulo: "La oreja de la que no habla", minutos: 5.3 },
      { titulo: "La viuda que inventó a Van Gogh", minutos: 5.3 },
    ],
  },
  {
    id: "vidas-vasari",
    titulo: "Las vidas de los más excelentes pintores, escultores y arquitectos",
    autor: "Giorgio Vasari",
    ano: 1550,
    gancho: "Casi todo lo que crees saber sobre los artistas del Renacimiento lo escribió un pintor de Arezzo que conocía a la mitad de ellos.",
    porQue: "Es el primer libro de historia del arte que se escribió, y sigue siendo la fuente de casi todas las anécdotas que circulan sobre Giotto, Leonardo o Miguel Ángel. También es donde nacieron algunos de los errores que todavía repetimos.",
    minutos: 23.8,
    capitulos: [
      { titulo: "Una cena en casa del cardenal", minutos: 4.8 },
      { titulo: "El niño que dibujaba ovejas", minutos: 4.8 },
      { titulo: "Las puertas del Paraíso", minutos: 4.7 },
      { titulo: "El funeral de San Lorenzo", minutos: 4.8 },
      { titulo: "El muro de la Sala de los Quinientos", minutos: 4.7 },
    ],
  },
  {
    id: "espiritual-arte",
    titulo: "De lo espiritual en el arte",
    autor: "Vasili Kandinsky",
    ano: 1911,
    gancho: "El libro con el que un pintor se dio permiso para dejar de pintar cosas. Su teoría del color es casi toda falsa y aun así cambió lo que se cuelga en las paredes.",
    porQue: "Porque explica de dónde salió el arte abstracto, que es lo que más incomoda al visitante de un museo. Y enseña una manera concreta de mirar un cuadro que no representa nada, que es dejar de preguntar qué es.",
    minutos: 24,
    capitulos: [
      { titulo: "Un cuadro apoyado del revés", minutos: 4.9 },
      { titulo: "El amarillo suena a trompeta", minutos: 4.9 },
      { titulo: "La necesidad interior", minutos: 4.8 },
      { titulo: "La mujer que llegó cuatro años antes", minutos: 4.8 },
      { titulo: "Del Bauhaus a la pared del salón", minutos: 4.7 },
    ],
  },
  {
    id: "reproductibilidad",
    titulo: "La obra de arte en la época de su reproductibilidad técnica",
    autor: "Walter Benjamin",
    ano: 1936,
    gancho: "Un refugiado alemán sin trabajo escribió en un café de París por qué una foto de un cuadro no es el cuadro. Cuatro años después murió en la frontera española.",
    porQue: "Es el ensayo del que salió todo lo que se dice hoy sobre imágenes, copias y originales. Y casi nadie lo lee: se citan cuatro frases suyas, casi siempre al revés de lo que él quería decir.",
    minutos: 22.5,
    capitulos: [
      { titulo: "El Instituto en el exilio", minutos: 4.5 },
      { titulo: "El aura", minutos: 4.8 },
      { titulo: "La sala de montaje", minutos: 4.6 },
      { titulo: "El estadio de Núremberg", minutos: 4.2 },
      { titulo: "Portbou, 26 de septiembre de 1940", minutos: 4.3 },
    ],
  },
  {
    id: "heroe-mil-caras",
    titulo: "El héroe de las mil caras",
    autor: "Joseph Campbell",
    ano: 1949,
    gancho: "Un hombre sin doctorado, que se pasó cinco años sin trabajo leyendo nueve horas al día en una cabaña, escribió el esquema con el que se construyen hoy la mitad de las películas de Hollywood.",
    porQue: "Porque su estructura funciona sorprendentemente bien para escribir historias y es bastante mala como descripción de la mitología del mundo, y casi nadie distingue las dos cosas.",
    minutos: 22,
    capitulos: [
      { titulo: "Cinco años leyendo en una cabaña", minutos: 4.5 },
      { titulo: "El monomito", minutos: 4.2 },
      { titulo: "El rancho Skywalker, 1983", minutos: 4.5 },
      { titulo: "Los mitos que no encajan", minutos: 4.6 },
      { titulo: "La diosa y la tentadora", minutos: 4.1 },
    ],
  },
  {
    id: "el-elemento",
    titulo: "El elemento",
    autor: "Ken Robinson",
    ano: 2009,
    gancho: "La charla más vista de la historia de TED se apoya en una estadística que la NASA nunca hizo. Y el argumento, curiosamente, aguanta igual sin ella.",
    porQue: "Porque es el libro que convenció a media docena de generaciones de que el colegio les había escondido algo. Vale la pena separar lo que Robinson demostró de lo que solo contó bien, porque las dos cosas están mezcladas y la segunda es la que más se repite.",
    minutos: 25,
    capitulos: [
      { titulo: "Una niña que no paraba quieta", minutos: 5 },
      { titulo: "Diecinueve minutos en Monterrey", minutos: 5 },
      { titulo: "El test que la NASA nunca hizo", minutos: 5.1 },
      { titulo: "La escuela que dicen que es una fábrica", minutos: 4.9 },
      { titulo: "Lo que aguanta cuando le quitas las cifras", minutos: 5 },
    ],
  },
  {
    id: "mujercitas",
    titulo: "Mujercitas",
    autor: "Louisa May Alcott",
    ano: 1868,
    gancho: "Le encargaron un libro para chicas. Escribió en su diario que no le apetecía nada, que nunca le habían gustado las chicas y que no conocía a ninguna aparte de sus hermanas. Lo terminó en diez semanas.",
    porQue: "Porque el libro que enseñó a varias generaciones de mujeres que se podía querer otra cosa lo escribió alguien que estaba negociando, capítulo a capítulo, con lo que su editor le dejaba escribir.",
    minutos: 22.1,
    capitulos: [
      { titulo: "Fruitlands, siete meses", minutos: 4.5 },
      { titulo: "Un libro para chicas", minutos: 4.2 },
      { titulo: "No voy a casar a Jo con Laurie", minutos: 4.4 },
      { titulo: "La casa de Concord", minutos: 4.6 },
      { titulo: "El escritorio entre dos ventanas", minutos: 4.4 },
    ],
  },
  {
    id: "cuentos-poe",
    titulo: "Cuentos de Edgar Allan Poe",
    autor: "Edgar Allan Poe",
    ano: 1845,
    gancho: "Inventó el relato de detectives, fijó las reglas del cuento moderno y escribió el poema más famoso de su país. Cobró nueve dólares por él y murió nueve años después, delirando, con la ropa de otro hombre.",
    porQue: "Porque casi todo lo que la gente cree saber de él lo escribió el hombre que lo odiaba, y porque su fama de autor de terror esconde que inventó dos géneros enteros.",
    minutos: 22,
    capitulos: [
      { titulo: "Un huérfano en Richmond", minutos: 4.1 },
      { titulo: "El hombre del tomahawk", minutos: 4.5 },
      { titulo: "El corazón debajo del suelo", minutos: 4.5 },
      { titulo: "El cuervo y los nueve dólares", minutos: 4.4 },
      { titulo: "Baltimore, 3 de octubre de 1849", minutos: 4.5 },
    ],
  },
  {
    id: "elegancia-erizo",
    titulo: "La elegancia del erizo",
    autor: "Muriel Barbery",
    ano: 2006,
    gancho: "Una portera de cincuenta y cuatro años finge ser tonta durante veintisiete años para que la dejen en paz, mientras lee a Tolstói y a Husserl en el cuarto de atrás.",
    porQue: "Porque vendió millones de ejemplares por el boca a boca y porque su idea de fondo —que la cultura es la verdadera aristocracia— es a la vez lo que lo hace emocionante y lo que lo hace tramposo.",
    minutos: 21.8,
    capitulos: [
      { titulo: "La portera del número 7", minutos: 4.2 },
      { titulo: "Una niña con fecha", minutos: 4.4 },
      { titulo: "Todas las familias felices se parecen", minutos: 4.6 },
      { titulo: "La furgoneta de la tintorería", minutos: 4.3 },
      { titulo: "Camelias sobre el musgo", minutos: 4.4 },
    ],
  },
  {
    id: "el-tunel",
    titulo: "El túnel",
    autor: "Ernesto Sabato",
    ano: 1948,
    gancho: "Lo escribió un doctor en física que había trabajado en el laboratorio Curie y que a los treinta y cuatro años abandonó la ciencia para siempre. Es la mejor novela en español sobre un razonamiento impecable que termina en un crimen.",
    porQue: "Porque en ciento cincuenta páginas enseña algo que no se aprende de otra manera: cómo se construye una certeza absoluta a partir de nada, paso a paso, sin que ninguno de los pasos sea ilógico. Y porque casi todo el mundo la lee olvidando quién la está contando.",
    minutos: 26.2,
    capitulos: [
      { titulo: "El primer párrafo dice quién y a quién", minutos: 5.3 },
      { titulo: "Una ventanita en la esquina de un cuadro", minutos: 5.2 },
      { titulo: "La cadena de razonamientos", minutos: 5.2 },
      { titulo: "Todo lo que sabemos de María", minutos: 5.3 },
      { titulo: "Dos túneles paralelos", minutos: 5.2 },
    ],
  },
  {
    id: "renglones-torcidos",
    titulo: "Los renglones torcidos de Dios",
    autor: "Torcuato Luca de Tena",
    ano: 1979,
    gancho: "Para escribirla, el director de un periódico nacional se hizo ingresar en un psiquiátrico durante dieciocho días. Solo el director del centro sabía que no estaba enfermo, y ni siquiera él sabía cómo iba a salir de allí.",
    porQue: "Porque plantea la pregunta más incómoda que existe: cómo demostrarías que estás cuerdo si nadie te creyera. Y porque el experimento científico que hizo esa misma pregunta seis años antes acabó, cuarenta años después, resultando bastante menos limpio de lo que decía.",
    minutos: 25.5,
    capitulos: [
      { titulo: "Dieciocho días de ingreso voluntario", minutos: 5.3 },
      { titulo: "Una detective que dice ser detective", minutos: 5 },
      { titulo: "El experimento que se le adelantó seis años", minutos: 4.9 },
      { titulo: "Los internos", minutos: 5.2 },
      { titulo: "Renglones torcidos", minutos: 5.2 },
    ],
  },
  {
    id: "cosas-buenas",
    titulo: "Cómo hacer que te pasen cosas buenas",
    autor: "Marian Rojas Estapé",
    ano: 2018,
    gancho: "Es probablemente el libro de divulgación más vendido en España en lo que va de siglo, y repite en cada capítulo una frase que es falsa tal y como está escrita.",
    porQue: "Porque su capítulo sobre el estrés crónico está bien y es útil, y porque su neurociencia de cuatro hormonas es una versión de manual popular que conviene saber leer con distancia.",
    minutos: 21.9,
    capitulos: [
      { titulo: "La hija del psiquiatra", minutos: 4.1 },
      { titulo: "El oso que no está", minutos: 4.7 },
      { titulo: "El circuito de la recompensa", minutos: 4.2 },
      { titulo: "Personas vitamina", minutos: 4.5 },
      { titulo: "La psiquiatra que dice que vayas al psiquiatra", minutos: 4.4 },
    ],
  },
  {
    id: "intro-psicoanalisis",
    titulo: "Introducción al psicoanálisis",
    autor: "Sigmund Freud",
    ano: 1917,
    gancho: "Veintiocho clases en las que un médico vienés intenta convencer a una sala llena de escépticos de que no somos dueños de nuestra propia cabeza.",
    porQue: "Es Freud explicándose a sí mismo para gente que no sabe nada, y por eso es la puerta de entrada. También es el sitio donde se ve mejor qué se sostiene de todo aquello y qué no.",
    minutos: 22.6,
    capitulos: [
      { titulo: "El anfiteatro de la Universidad de Viena", minutos: 4.6 },
      { titulo: "Los actos fallidos", minutos: 4.5 },
      { titulo: "El taller de los sueños", minutos: 4.4 },
      { titulo: "El diván de Berggasse 19", minutos: 4.5 },
      { titulo: "La casa de Maresfield Gardens", minutos: 4.5 },
    ],
  },
];

/** Índice por identificador, que es como lo pide la pantalla. */
export const META_POR_ID: Record<string, FichaMeta> = Object.fromEntries(
  META.map((f) => [f.id, f]),
);
